### ISSUE TITLE
Change the offset based on the direction?

### ISSUE THREAD

**Issue by RyanHavoc** [imakewebthings/waypoints#12]
Hi,

I have a number of waypoint elements that basically trigger the fade in and out of a nav bar which gets repositioned to be at the top element currently in view.

This works fine and the waypoint event is triggered when I scroll past the top of the elements.

What I ideally want is for the event to be triggered both when you scroll past the top and bottom of the elements if that makes sense?

I know there's offset: 'bottom-in-view' but what I want is for it to trigger for both bottom-in-view or "top-in-view".

A) Is this possible and B) Is something like this along the right lines?

``` js
{offset: function() {

if(#NOT SURE WHAT TO CHECK FOR@) {
    return $.waypoints('viewportHeight') - $(this).outerHeight();
} else {
    return 0;
}
}
```

Would appreciate any help.

Thanks

Ryan

**Comment by stratboy** [comment]
I think the best solution here, is the one detailed on SO:

https://stackoverflow.com/questions/19181435/different-offset-for-jquery-waypoint-up-event

Basically, create 2 waypoints per element, with different offsets, and make a guard for the direction.
My personal take (assume a sections array):

``` js
sections.forEach(function(section, index){
  waypoint_down = new Waypoint({
    element: section,
    handler: function(direction){
      if(direction == 'up') return;
      [do things]
    },
    offset: [down offset]
  });

  waypoint_up = new Waypoint({
    element: section,
    handler: function(direction){
      if(direction == 'down') return;
      [do things]
    },
    offset: [up offset]
  });
});
```
