### ISSUE TITLE
Sticky nav unsticks only in FF

### ISSUE THREAD

**Issue by ahirschbeck-ut** [imakewebthings/waypoints#13]
Hi! 
This functionality is pretty incredible. I'm using the sticky nav functionality and when I refresh from my browser, the sticky unsticks. 
I've tested in Safari and IE and it's working fine in those browsers, any ideas? 
Thanks in advance for your help!

**Comment by prabhumachismo** [comment]
I'm having an issue in removing sticky when the scrolling crossed the waypoint..

For more info:
https://github.com/imakewebthings/waypoints/issues/592
