### ISSUE TITLE
iPhone scroll behaviour Question

### ISSUE THREAD

**Issue by katerlouis** [imakewebthings/waypoints#258]
This is more of a question than an issue.
On the project site "Get started" you trigger example notifications via a function called by the waypoint-function itself.

Usually the iPhone doesnt allow any DOM-manipulation while scrolling. But somehow the notifications on this particular page get triggered even if I dont stop scrolling. I copied your notify-function and the waypoint function. On my page it doesnt work that way- it triggers when I stop scrolling.

Please Sir! I beg you to tell me and all the other people out there how you made the iPhone react in realtime while scrolling on "Get started" notification examples.

(although I'm sure this must be a bug or something, because otherwise you would have also implemented this in the sticky feature etc., I still hope you can tell why live triggerin works on this page- because.. it does :) And this is awesome!)

THX!

**Comment by sdras** [comment]
It would be really nice to have something like this in the docs because it saved me a ton of time. Thank you!

**Comment by imakewebthings** [comment]
@sdras Good thinking. 👏  #489 is now open to track this.

**Comment by evanlarsen** [comment]
The sticky elements doesn't work till end of scroll on Iphone 6s.  iOS 6.3.1.

I think the issue of "the iPhone doesn't allow any DOM-manipulation while scrolling" still exists on short cuts page for sticky elements.

On the guides page the toast notifications work perfectly for some reason. I'm not sure how some DOM manipulation is allowed and others aren't.
