### ISSUE TITLE
Duplicate items on infinite scroll

### ISSUE THREAD

**Issue by ryanscherler** [imakewebthings/waypoints#316]
I am using the infinite scroll extension of waypoints and for some reason its loading duplicate content on each request. See example:

http://themazamastore.ryanscherler.com/goats-blahg/ (loads the first 9 items)

`
    $('.content-grid').waypoint('infinite', {
        container: 'auto',
        items: '.post',
        more: '.MarkupPagerNavNext a'
    });
`

You can access the requested page(s) (next page of 9 items)

http://themazamastore.ryanscherler.com/goats-blahg/page-2

Any ideas why this would be happening? Am I supposed to somehow remove the elements already loaded? Maybe some sort of caching?

**Comment by pmkhoa** [comment]
I was successfully replicated this issue. If you keep scrolling when it reaches the bottom of the browser, it will trigger several ajax requests. This appears to happens in Chrome only.

**Comment by rawzone** [comment]
I also have this issue on a Wordpress site where we are using the infinite scroll shortcut.
When going back and forward and starting to scroll it seems like it keeps loading items after the "loop" should have ended..
