### ISSUE TITLE
Waypoint elements firing on page load

### ISSUE THREAD

**Issue by petephm** [imakewebthings/waypoints#355]
I'm using waypoints to hide and show elements at certain scroll points,
however when the page loads waypoints fires before #back_to_top is 'bottom-in-view' and adds then removes the classes, which results in the elements flashing on load.

This is my js:

```
var stickyHeader = new Waypoint({
    element: document.getElementById('sticky_header'),
        handler: function() {
        $('#sticky_header').toggleClass('is_visible');
        $('#back_to_top').toggleClass('is_rotated');
    },
    offset: '-25%'
});
var footerAppear = new Waypoint({
    element: document.getElementById('back_to_top'),
    handler: function() {
        $('#back_to_top').toggleClass('is_fixed');
        $('#layered_logo').toggleClass('is_hidden');
    },
    offset: 'bottom-in-view'
});
```

**Comment by martinlemahieu** [comment]
@imakewebthings : I'm working on a page where I have two sticky elements : one stick to the top (like a sticky header) the other stick to the bottom (the goal is to have this element always visible on the page load, even for small resolutions). My problem is that when I instantiate the waypoint for the element that stick on the bottom, even if he is under the bottom of the viewport, he is not trigger in the up direction (not like my stick-to-the-top navbar which is triggered in the down direction if I load the page to a location that crossed the waypoint). (I'm sorry for my english skill)
Is this an expected bahavior of waypoints to trigger only the down direction when you initiate a waypoint or am I doing something wrong ?

**Comment by nicbou** [comment]
For those using the Inview shortcut, you can create disabled waypoints by overriding the createWaypoint prototype to add the 'enabled: false' line:

```javascript
    Inview.prototype.createWaypoint = function(config) {
        var self = this;
        this.waypoints.push(new Waypoint({
            element: this.options.element,
            handler: (function(config) {
                return function(direction) {
                    self.options[config[direction]].call(this, direction);
                };
            }(config)),
            offset: config.offset,
            horizontal: this.options.horizontal,
            enabled: false, //here is the modified line
        }));
    };
```

@imakewebthings, do you think there could be a better way to supply such options?

**Comment by imakewebthings** [comment]
@nicbou I'm game for adding the enabled option to Inview. I think this would naturally also come with a change to add `enable` and `disable` methods that would enable and disable all the underlying waypoints. Could you open a new issue with that request? Thanks.

**Comment by sebastianwebb** [comment]
Perhaps it's something to do with my setup, but I found that I needed to introduce a little delay before re-enabling waypoints initiated with **enabled: false**

```
var waypoint = new Waypoint({
  element: document.getElementById('basic-waypoint'),
  enabled: false,
  handler: function() {
    notify('Basic waypoint triggered')
  }
});

setTimeout(function(){
  waypoint.enable();
}, 250);

```
Otherwise off-page elements fired all 4 of the InView event handlers with the down direction

I was using the no-framework Waypoints and the InView shortcut.

**Comment by FarrisFahad** [comment]
I had a similar issue. I changed the Waypoint CSS class overflow: from Visible to auto. And it worked for me.

**Comment by corsaronero** [comment]
Hi try this solution, activate waypoint when the scroll is different from 0:

$(function () {

            $(window).scroll(function () {
                if ($(this).scrollTop() > 0) {
                    waypoint.enable();
                    waypoint1.enable();
                    waypoint2.enable();
                }
            });

            try {
                /* ================ ANIMATED CONTENT GALLERY ================ */

                var waypoint = new Waypoint({
                    element: document.getElementById('level1'),
                    enabled: false,
                    handler: function (direction) {
                        console.log(direction);
                        if (direction === 'down') { $(this.element).addClass("animate-img");  }
                    },
                    offset: '35%',

                });

                var waypoint1 = new Waypoint({
                    element: document.getElementById('level2'),
                    enabled: false,
                    handler: function (direction) {
                        if (direction === 'down') { $(this.element).addClass("animate-img");  }
                    },
                    offset: '35%',

                });

                var waypoint2 = new Waypoint({
                    element: document.getElementById('level3'),
                    enabled: false,
                    handler: function (direction) {
                        if (direction === 'down') { $(this.element).addClass("animate-img"); }
                    },
                    offset: '35%',

                });

            } catch (err) {

            }

        });

Cheers

**Comment by speedygonzales77** [comment]
> Perhaps it's something to do with my setup, but I found that I needed to introduce a little delay before re-enabling waypoints initiated with **enabled: false**
> 
> ```
> var waypoint = new Waypoint({
>   element: document.getElementById('basic-waypoint'),
>   enabled: false,
>   handler: function() {
>     notify('Basic waypoint triggered')
>   }
> });
> 
> setTimeout(function(){
>   waypoint.enable();
> }, 250);
> ```
> Otherwise off-page elements fired all 4 of the InView event handlers with the down direction
> 
> I was using the no-framework Waypoints and the InView shortcut.

This worked for me. I was trying to prevent the Waypoint to trigger when the page was loaded with div already scrolled to the top or when it was in screen view.

**Comment by boozeahead** [comment]
@imakewebthings 
For This issue.
Do we Still have to use [this](http://imakewebthings.com/waypoints/guides/debugging/)?
