### ISSUE TITLE
Mobile safari

### ISSUE THREAD

**Issue by cheshirecatalyst** [imakewebthings/waypoints#357]
Mobile safari form assistant causes waypoint to fire in a 'random' manner, causing a handler which modifies the dom to fire, closing the form assistant.

**Comment by imakewebthings** [comment]
From the Contributing Guidelines:

> If you're opening a ticket for a bug:
>
> - Give a clear explanation of the bug.
> - Try to provide a link to a JSFiddle or CodePen or similar reduced test case.
> - If you cannot provide a reduced test case, please provide a link to a live site demonstrating your bug and include in the ticket the relevant Waypoints code.

I'd love to see an example, though I do believe I understand what you're getting at by the description. And if I understand right, I'm not sure what I can do from the Waypoints library perspective. Perhaps you could call [waypoint.disable()](http://imakewebthings.com/waypoints/api/disable/) on the offending waypoint when the form element is focused? Again, it's hard to say without seeing the concrete use case.

**Comment by imakewebthings** [comment]
Closing. Reopen if there is more to add.
