### ISSUE TITLE
Cannot read property 'top' of null

### ISSUE THREAD

**Issue by pinesbrook** [imakewebthings/waypoints#358]
I was getting this error while using noframework.waypoints.js, until I changed line 370 from
elementOffset = waypoint.adapter.offset()[axis.offsetProp]
to 
elementOffset = waypoint.element.offset()[axis.offsetProp]

**Comment by imakewebthings** [comment]
I'm going to need more information than this to tell if this is actually a bug. From the Contributing Guidelines:

> If you're opening a ticket for a bug:
>
> - Give a clear explanation of the bug.
> - Try to provide a link to a JSFiddle or CodePen or similar reduced test case.
> - If you cannot provide a reduced test case, please provide a link to a live site demonstrating your bug and include in the ticket the relevant Waypoints code.

Also, the noframework adapter has a good reason to return `null` from `offset`. https://github.com/imakewebthings/waypoints/blob/2628c9077598fcf66030890f51831d88be1a3f78/src/adapters/noframework.js#L67-L69 If your waypoint element isn't anywhere in the DOM (and thus has no position in it.)

**Comment by pinesbrook** [comment]
My apologies, I was way too quick on the trigger here, and now I see there is no way I can delete this issue. That check of the ownerProperty was where my own issue was; the element had accidentally been wrapped up as a Zepto $ collection (of one), before eventually getting passed in as the waypoint element. And therefore as you said, it couldn't be said to be anywhere in the DOM. Thanks very much for your guidance and for your work.

**Comment by imakewebthings** [comment]
@pinesbrook No worries about the quick trigger. Don't delete the issue. These things are useful for others who come across the same issue. Happy coding!

**Comment by MartinMuzatko** [comment]
Just came across this info. Thanks for providing the issue :)

**Comment by mortennajbjerg** [comment]
Yeah - I had this too problem too. Solution for jQuery:
Instead of this...:
```
var waypoint = new Waypoint({
  element: $elem,
  handler: function(dir) { 
    // Code
  }
});
```
... do this:
```
var waypoint = new Waypoint({
  element: $elem[0],
  handler: function(dir) { 
    // Code
  }
});
```
... and You should be allright :)

**Comment by ronanmccoy** [comment]
Found this, now closed, issue after googling the following browser error:

"TypeError: f.adapter.offset(...) is null"

The solution offered by mortennajbjerg on Aug. 4th worked for me. I was using noframework.waypoints.js, the inview.js addon, in conjunction with skrollr.js.

**Comment by vnussolution** [comment]
Thanks mortennajbjerg, your trick works for me!
