### ISSUE TITLE
CDNJS

### ISSUE THREAD

**Issue by hyptx** [imakewebthings/waypoints#368]
Any plans of adding this to the cdnjs library? jQuery Waypoints is there.

**Comment by imakewebthings** [comment]
@hyptx Thanks for opening this ticket. I do want to update the CDNJS info for the 3.x changes. I'm going to wait for #339 to be resolved, which will make future CDNJS updates easier in the future.

**Comment by hyptx** [comment]
Awesome, I load all my scripts from there, can't wait. Thanks.

**Comment by Wtower** [comment]
Thanks for all your efforts. That would be nice for me too. Subscribing.

**Comment by Wtower** [comment]
Of course, jsut for the record, there is always the possibility to use the [RawGit](http://rawgit.com/) service as well.

**Comment by JoeHana** [comment]
+1 - any updates on that yet?

**Comment by macx** [comment]
It's [up-to-date](https://cdnjs.com/libraries/waypoints), ticket can be closed.
