### ISSUE TITLE
Bower failing due to repository disabled

### ISSUE THREAD

**Issue by eboto** [imakewebthings/waypoints#370]
This is a bit baffling, but as of a few minutes ago when I try to `bower update` my application, I get the following error:

bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/imakewebthings/waypoints.git", exit code of #128

Additional error details:
fatal: remote error: 
  Repository "imakewebthings/waypoints" is disabled. Please ask the owner to check their account.

Now, it seems to me that this repository is not, in fact, disabled so I'm unsure where this error is coming from. Do you have any idea?

**Comment by matmar10** [comment]
I am getting the same issue.

**Comment by dpogue** [comment]
+1

**Comment by dexdexdex** [comment]
We're seeing the same thing over here. It's breaking our build too.

**Comment by levity** [comment]
+1

**Comment by eckyputrady** [comment]
+1 here

**Comment by colinkahn** [comment]
+1 same here

**Comment by kieferhagin** [comment]
+1 here also

**Comment by jayzeng** [comment]
+1 here

**Comment by agustinus-kristiadi** [comment]
+1

**Comment by benjaminliugang** [comment]
+1

**Comment by matmar10** [comment]
Note if you're depending on waypoints just for using angularitics and google analytics, I suggest the following quick-and-dirty (yet effective) replacement: 

```
'use strict';
 
angular.module('yourAppName')
  .run(['$state', '$rootScope', '$timeout', function ($state, $rootScope, $timeout) {
    /* global ga */
    // clear errors when changing state
    $rootScope.$on('$stateChangeSuccess', function () {
      // wait until hash change is propogated at end of scope digest cycle
      $timeout(function () {
        ga('send', 'pageivew', window.location.hash.substring(1));
      });
    });
  }]);
```

**Comment by imakewebthings** [comment]
Investigating, folks. Thanks for the alert.

**Comment by glauberramos** [comment]
+ 1 here, this is breaking the build for my app

**Comment by mattly** [comment]
+1000 this is breaking our build.

**Comment by mattly** [comment]
in the meantime, can you at least enable cloning of this repo so we can get at old versions of the lib?

```
~/projectdir> git clone git@github.com:imakewebthings/waypoints.git
Cloning into 'waypoints'...
ERROR: Repository `imakewebthings/waypoints' is disabled. Please ask the owner to check their account.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by imakewebthings** [comment]
Hi Everyone,

Can you please give your builds and/or cloning another try? I believe this was a temporary internal GH glitch that blocked git:// access to the repository and appears from my end to be resolved now. Let me know. Thank you.

**Comment by eboto** [comment]
Works!

**Comment by dexdexdex** [comment]
Looks good to me!

**Comment by sasyomaru** [comment]
Works!

**Comment by eboto** [comment]
Thanks for addressing it so quickly, señor.

**Comment by eboto** [comment]
Life saver. I had just been sitting at my workstation, running `bower update` over and over while eating a tub of ice cream and weeping onto my fat face.

**Comment by jayzeng** [comment]
@eboto :laughing:

**Comment by imakewebthings** [comment]
To be clear, I basically did nothing but email GitHub support. Thank one of those fine people next time you see one.

**Comment by jden** [comment]
I mean, it's working now +1
