### ISSUE TITLE
Error in IE8 - 'left' is null or not an object

### ISSUE THREAD

**Issue by mikeebee** [imakewebthings/waypoints#372]
Hi, I'm using the jQuery version (3.0.1) as I need IE8 support, but I'm getting this error.

jQuery version 1.10.2

``` 'left' is null or not an object ```

The line number that this is referring to (according to the error in IE) is ```350```, this part...

``` 
horizontal: {
        contextOffset: isWindow ? 0 : contextOffset.left,
        contextScroll: isWindow ? 0 : this.oldScroll.x,
        contextDimension: this.innerWidth(),
        oldScroll: this.oldScroll.x,
        forward: 'right',
        backward: 'left',
        offsetProp: 'left'
      },
```

Any ideas?

**Comment by imakewebthings** [comment]
Are you able to provide me with a link to the site where this is happening, or some kind of JSFiddle/Codepen that shows it happening? Could you also include here the Waypoints code you've written that results in this error? Thanks.

**Comment by mikeebee** [comment]
I can't make the page public but I've just messaged you with details, I hope that's ok. Thanks!

**Comment by heybenji** [comment]
I am also having this issue in IE8.

**Comment by imakewebthings** [comment]
Yep, this is an issue with my `isWindow` function. Apparently `element.window` is undefined before IE 9. I'll get a fix in and cut a new version soon. Look for the fix in 3.1.1. I'll post here when that release is out.

**Comment by heybenji** [comment]
@mikeebee if you're not trying to do anything fancy (which I am not) and you're using jQuery (which you are), I found that downgrading to 2.0.5 (https://github.com/imakewebthings/waypoints/releases/tag/v2.0.5) solved my issue for the time-being.

**Comment by heybenji** [comment]
Hey @imakewebthings thanks for looking into this without a lot of detail from me (at least). Looking forward to 3.1.1.

Benji

**Comment by imakewebthings** [comment]
`3.1.1` is now out. @heybenji @mikeebee could you download and give it a try? Thanks.

**Comment by mikeebee** [comment]
Has the lib directory been updated? I'm not seeing a difference in the files.

**Comment by imakewebthings** [comment]
@mikeebee I definitely see the update in the `lib` files. How are you getting your updates?

**Comment by mikeebee** [comment]
From the github master page, this is what I'm seeing. Apologies if I'm missing something! It looks like the src folder is the only thing that was updated.

![Image of Version](http://mikeebee.com/other/version.jpg)

**Comment by imakewebthings** [comment]
@mikeebee Weird. I see another commit past that and when I DL from the project page I get the 3.1.1 release code. Maybe do a hard refresh on that page? Could be a GH caching thing that will resolve itself soon?

**Comment by mikeebee** [comment]
Just cleared my browser cache and the latest code has appeared!

Delighted to report that it's now working great in IE8. Thanks so much!

(@heybenji, thanks for the suggestion earlier)

**Comment by heybenji** [comment]
@imakewebthings just as an additional confirmation, I upgraded back to 3.1.1 and everything is peachy-keen. Thanks so much for releasing a fix so quickly.
