### ISSUE TITLE
Waypoints function only triggering on screen resize.

### ISSUE THREAD

**Issue by lukephills** [imakewebthings/waypoints#376]
Hi there, 

Waypoints is only firing on the screen resize in this wordpress site. I've tried deactivating all plugins but it doesn't make any difference. Have you seen this happen before? What am I doing wrong?

The .manual-item elements that i'm watching are the yellow boxes. You can see in this example video:
https://drive.google.com/open?id=0B-FXQg_VQV3JQ1ZBQWxVRHUxOUE&authuser=0

And heres my code:
Line 40: https://github.com/lukephills/Kollektiv/blob/master/assets/js/app.js

Many thanks

**Comment by imakewebthings** [comment]
Do you have a link I could play with?

**Comment by lukephills** [comment]
Here's a link http://codepen.io/lukeyphills/pen/zxpVQR?editors=100

**Comment by lukephills** [comment]
I worked it out in the end. I had both overflow: hidden; and overflow-y: scroll; on my container. 

As soon as I removed that the functions fire immediately. Thanks
