### ISSUE TITLE
Can't destroy waypoints

### ISSUE THREAD

**Issue by peterph-am** [imakewebthings/waypoints#378]
I'm having some issues trying to destroy waypoints when the browser width is a certain size

I get a console error:
![image](https://cloud.githubusercontent.com/assets/7984905/6208747/93bd642e-b611-11e4-95fc-8053c10475bc.png)

![image](https://cloud.githubusercontent.com/assets/7984905/6208761/bb1c98be-b611-11e4-84c4-db241375638f.png)

Am I using the destroy method wrong?

````
// Variables
var $project_item = $(".projects_list > li"),
      hide_all = $project_item.not(':first').addClass('is_hidden');

// Init Waypoints
var show_project = $project_item.waypoint(function() {
   var _this = $(this.element);

   $project_item.addClass('is_hidden');
   _this.removeClass('is_hidden');
}, {
   offset: '0%'
});

// Destroy Event
if (VPW < 768) {
   show_project.destroy();
]}
````

**Comment by imakewebthings** [comment]
`$.fn.waypoint` returns an **array** of waypoints. You are trying to call destroy on an array. You need to loop over the array and invoke `destroy`.

**Comment by peterph-am** [comment]
Could you please write an example? Thanks

**Comment by imakewebthings** [comment]
@peterph-am Could you write an example of how you think one might loop over an array in JavaScript and call a method on each item in that array?

**Comment by peterph-am** [comment]
I'm pretty new to loops in javascript, but i tried this: 

````
$project_item.each(function() {
    $.fn.waypoint.destroy();
});
````

But I'm still getting a error. Some guidance would be much appreciated thanks.
