### ISSUE TITLE
Trigger once?

### ISSUE THREAD

**Issue by alexcroox** [imakewebthings/waypoints#381]
The old plugin used to have a trigger once option, I can't seem to find it in the new documentation.

**Comment by stehefan** [comment]
You can see it in the documentation at this place: http://imakewebthings.com/waypoints/api/destroy/

In short: trigger-once is not available anymore, but you're able to call 
```
this.destroy
```
at the end of your handler, resulting in the destruction of the handler at the first call of the handler.

**Comment by alexcroox** [comment]
Ah great, thank you very much.
