### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by osricmacon** [imakewebthings/waypoints#387]
I am using your wonderful library for quite some time and have never faced any issues.

i have a simple code 

	jQuery(".theo-chart").each(function () {
		  jQuery(this).waypoint(function () {
			var tSize = jQuery(this).attr("data-t-size"),
			  tLineWidth = jQuery(this).attr("data-t-line"),
			  tBarColor = jQuery(this).attr("data-t-barColor"),
			  tTrackColor = jQuery(this).attr("data-t-trackcolor"),
			  tScaleColor = jQuery(this).attr("data-t-scalecolor") || false,
			  tScaleLength = jQuery(this).attr("data-t-scalelength") || false,
			  tLineCap = jQuery(this).attr("data-t-linecap") || "round",
			  tAnimationDuration = jQuery(this).attr("data-t-animationduration") || 1000,
			  tEasing = jQuery(this).attr("data-t-easing") || "easeOutQuad",
			  tRotate = jQuery(this).attr("data-t-rotate") || 0;
			jQuery(this).easyPieChart({
			  animate: {
				duration: tAnimationDuration,
				enabled: true
			  },
			  barColor: tBarColor,
			  trackColor: tTrackColor,
			  lineWidth: tLineWidth,
			  size: tSize,
			  lineCap: tLineCap,
			  scaleColor: tScaleColor,
			  scaleLength: tScaleLength,
			  easing: tEasing,
			  rotate: tRotate,
			  onStart: function () {
				jQuery(this.el).css({
				  'height': tSize,
				  'width': tSize,
				  'lineHeight': tSize + 'px'
				});
				jQuery(this.el).find('i').css('lineHeight', tSize + 'px');
			  },
			  onStep: function (from, to, percent) {
				jQuery(this.el).find('.percent').text(Math.round(percent) + '%').css('color', tBarColor);
			  }
			});
		  }, {
			triggerOnce: true,
			offset: 'bottom-in-view'
		  });
		});

It use to work fine with jQuery Waypoints - v2.0.5
Now i have upgrade it to latest jquery buld of your and it says waypoint is undefined.

Can you please help?

**Comment by imakewebthings** [comment]
@osricmacon This repository follows [semver](http://semver.org/). Changes to the major version, from 2 to 3, includes breaking changes. If you want to upgrade it is possible that you may have to change things to conform to the new API.

That said, this shouldn't cause the error you're seeing. Are you sure you're including the jQuery build of Waypoints?

There is a different, unrelated thing you **will** have to change. `triggerOnce` was eliminated. You should now call `this.destroy()` at the end of your handler function.

**Comment by osricmacon** [comment]
thanks
