### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by DEATHMETALGORE** [imakewebthings/waypoints#388]
I tried tying this plugin to a Bootstrap 3 navbar and this is the error I am getting:

```
Uncaught TypeError: Cannot read property 'extend' of undefinedwebvana.js:2320 Waypointapp.js:20 Sticky.createWaypointapp.js:13 Stickyapp.js:96 (anonymous function)jquery.min.js:2 n.Callbacks.jjquery.min.js:2 n.Callbacks.k.fireWithjquery.min.js:2 n.extend.readyjquery.min.js:2 K
```

This is the line we're talking about:
```
this.options = Waypoint.Adapter.extend({}, Waypoint.defaults, options)
```

And this is how I set it up:
```
var sticky = new Waypoint.Sticky({
    element: $('.main-menu')[0]
})
```
What could be causing this?

**Comment by imakewebthings** [comment]
@DEATHMETALGORE It's hard to say without seeing this in the wild. Do you have a page I could look at?

**Comment by DEATHMETALGORE** [comment]
It was my mistake. I used the wrong library in my project. I was supposed to use the jQuery version of this plugin.
