### ISSUE TITLE
Cannot create disabled inviews

### ISSUE THREAD

**Issue by nicbou** [imakewebthings/waypoints#389]
In relation to: https://github.com/imakewebthings/waypoints/issues/355#issuecomment-81413958

It would be useful to be able to specify that we want to create inviews with disabled waypoints to deal with the behavior pinpointed in the ticket above.

**Comment by imakewebthings** [comment]
Thanks, @nicbou. This will be part of the next release but no idea when that will be.

**Comment by imakewebthings** [comment]
@nicbou This is part of the now released 4.0.0.
