### ISSUE TITLE
oldWindowLoad is not defined error

### ISSUE THREAD

**Issue by illepic** [imakewebthings/waypoints#390]
On jQuery 1.8 and Waypoints 3.1.1, I get the following error in *Chrome only*:

    Uncaught ReferenceError: oldWindowLoad is not defined        VM9050:2

The "VM9050" file appears to be a Chrome optimized file that looks like:

````
(function(e
/**/) {
{
    if (oldWindowLoad) {
      oldWindowLoad()
    }
    Context.refreshAll()
  };cY(e);
})
````

This all corresponds in jquery.waypoints.js, line 177:

    var oldWindowLoad = window.onload

And lines 449 - 454:

````
  window.onload = function() {
    if (oldWindowLoad) {
      oldWindowLoad()
    }
    Context.refreshAll()
  }
````

**Comment by imakewebthings** [comment]
@illepic Do you have a link you could share with me?

**Comment by illepic** [comment]
Hello! Unfortunately this site is being developed behind an htaccess wall, but I can get you any code info you need. I can post some screenshots of errors firing as well, will get those up now.

**Comment by illepic** [comment]
Here is the console error:

![oldWindowLoad is not define](https://dl.dropboxusercontent.com/s/1i6eg50o0t5uegs/2015-03-30%20at%206.48%20AM.png?dl=0)

And here is the VM19796:2 "file":

![VM19796 file](https://dl.dropboxusercontent.com/s/ossk66nye965362/2015-03-30%20at%206.51%20AM.png?dl=0)

**Comment by imakewebthings** [comment]
@illepic Are you using some kind of script loader that uses `eval` to execute Waypoints? I haven't found reason for Chrome to break up a script into a bunch of VM chunks outside of that, nor do I understand, even if you were, why Chrome would break it up in a way that broke references to variables that are clearly within the same scope.

**Comment by illepic** [comment]
After an update to Chrome, this appears to no longer be an issue. Thank you for your responses!
