### ISSUE TITLE
Wrong example on home page

### ISSUE THREAD

**Issue by zanematthew** [imakewebthings/waypoints#394]
Although this should probably be posted on your repo: https://github.com/imakewebthings/imakewebthings.github.com

the example on your home page for WayPoints, is wrong :)

```
var waypoint = new Waypoint({
  element: document.getElementById('#waypoint'), // '#waypoint', should just be 'waypoint'
  handler: function(direction) {
    console.log('Scrolled to waypoint!')
  }
})
```

**Comment by imakewebthings** [comment]
Yep, this should be changed. @zanematthew Would you like to make a PR to fix it? It isn't with my personal website repo, that code is in the `gh-pages` branch of this repository.

**Comment by zanematthew** [comment]
Great, np I definitly will :D thanks for pointing me to where it is.

On Sun, Mar 29, 2015 at 1:33 AM, Caleb Troughton <notifications@github.com>
wrote:

> Yep, this should be changed. @zanematthew <https://github.com/zanematthew>
> Would you like to make a PR to fix it? It isn't with my personal website
> repo, that code is in the gh-pages branch of this repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imakewebthings/waypoints/issues/394#issuecomment-87360397>
> .
>



-- 
Zane M. Kolnik
Founder
@zkolnik

Zane Matthew,  Inc.
Baltimore, MD 21230
*http://zanematthew.com <http://zanematthew.com/>*
http://twitter.com/zanematthew
http://github.com/zanematthew
(443)-821-00ZM
(443)-821-0096

The contents of this e-mail and any attachments are intended solely for the
use of the named addressee(s) and may contain confidential and/or
privileged information. Any unauthorized use, copying, disclosure, or
distribution of the contents of this e-mail is strictly prohibited by the
sender and may be unlawful. If you are not the intended recipient, please
notify the sender immediately and delete this email. Thank you.

**Comment by imakewebthings** [comment]
Fixed.
