### ISSUE TITLE
More lenient waypoint triggers

### ISSUE THREAD

**Issue by meowsus** [imakewebthings/waypoints#399]
I recently ran into an issue where I dynamically created a navigation for a style guide I was working on. I wanted to use waypoints to produce a Bootstrap-esque Style Guide menu: http://getbootstrap.com/css/

I realized that, with a default, simple implementation of waypoints, this was impossible. Scrolling up and down the page worked great. Clicking _down_ the list of generated ID anchors worked, but clicking _up_ the list of generated ID anchors did not work. This is because the anchor link did not trigger the waypoint because the anchor did not hit the threshold. It was always 1px lower when trying to navigate up the list.

No amount of configuration fixed this. If the `offset` was adjusted one _or_ the other would work.

I think that this is a pretty reasonable use case and that the plugin should trigger the waypoint event if the window is on the element, rather than one pixel _past_ the element.

**Comment by imakewebthings** [comment]
@meowsus This is a discussion that has come up in the issue tracker here a couple times. I'd love to lay out the full argument about why Waypoints works the way it does in this regard, but it's going to take a little more time than I have right now. Right now, if you want to start with https://github.com/imakewebthings/waypoints/issues/346#issuecomment-65501126 and browse from there... but I do have more to say on the topic!

**Comment by meowsus** [comment]
Thanks for the reference, @imakewebthings. I can see why this isn't implemented, but I do think it's a valid use case, since there doesn't seem to be a way to write a client module that manually triggers the waypoint event. I'm still struggling with the original implementation I wrote, so maybe consider a compromise -- an option that modifies the behavior for this use case.

Have a good one and, still, you've made a great piece of code here.
