### ISSUE TITLE
Multiple offsets/waypoints for one element

### ISSUE THREAD

**Issue by imakewebthings** [imakewebthings/waypoints#40]
I'd like to explore the best way to implement this.  At the very least, `waypoint.reached` would have to become just a general hook and not the end-all-be-all event that all this functionality centers around.

**Comment by bertyhell** [comment]
*EDIT*

never mind, i had to just put continuous on true.
```
continuous: true
```
https://jsfiddle.net/x16tmsck/2/

*EDIT*



> Version 2.0 is out and includes support for creating multiple waypoints on the same element.

I'm using version 4.0.0 but it doesn't seem to support multiple waypoints on one element.
Here is a minimal usage example
https://jsfiddle.net/x16tmsck/1/

it seems only the last waypoint is triggered

am i doing something wrong, or is the behavior not supported?
