### ISSUE TITLE
Trigger waypoint just before entering to the element

### ISSUE THREAD

**Issue by farukham** [imakewebthings/waypoints#400]
Hi,
How can i trigger waypoint on an element before it appears in the viewport?

**Comment by NiekPas** [comment]
Use offset. Example:

```
$('elementWithWaypoint').waypoint(function() 
            {
                $(".textToChange").fadeOut();
            },
            {
                offset: '30px'
            }
        );
```

This will make the waypoint trigger 30px *before* elementWithWaypoint enters the viewport.

**Comment by imakewebthings** [comment]
What @NiekPas said is not entirely accurate, but on the right track. @farukham, you should use offset, but `"30px"` (or just `30`) will make the element fire when the top of the element is 30 pixels from the **top** of the viewport. The way I've read your issue, you want to waypoint to trigger when the element just barely begins entering the viewport? If that's correct, the offset should be `"100%"`.
