### ISSUE TITLE
Transform causing wack fixed positioning

### ISSUE THREAD

**Issue by BenRacicot** [imakewebthings/waypoints#402]
I've been tracking a [bug](https://code.google.com/p/chromium/issues/detail?id=20574) regarding very unique scenarios where using transforms can cause fixed positioned elements to shoot out of screen.  Obviously this isn't directly related directly to waypoints as a library but I am assuming that users of this library might be suffering from this bug like I am with sticky elements and possibly know how to avoid it.

I cannot recreate it on jsfiddle or codepen but it is consistent across browsers on my local environment. when a waypoint becomes "stuck" the element jumps out of flow and is presumably at top:0 position regardless of its fixed positioning. Any help at all would be greatly appreciated, thanks. 

Here is my culprit CSS that I've tracked the issue to:
     
     //Culprit CSS!!
     //collapsed transform from http://responsivenavigation.net/
     -ms-transform: translate(0px, 0);
     -moz-transform: translate(0px, 0);
     -webkit-transform: translate3d(0px, 0, 0);
     transform: translate(0px, 0);`

**Comment by imakewebthings** [comment]
@BenRacicot I'm afraid I don't have any suggestions for escaping what is either, if I've read that tracker issue right, a bug or a correct spec implementation. There isn't anything I can do on my end.
