### ISSUE TITLE
Negative Bottom Offset for Infinite Scroll

### ISSUE THREAD

**Issue by hammertimedk** [imakewebthings/waypoints#404]
I can't quite seem to figure out looking at the Offset docs how to trigger infinite scrolling _before_ the container reaches the bottom, i.e. 'bottom-in-view' - Reason is, I don't like how users hit a hard bottom and then have to wait x milliseconds for the content to load - it would be great if the content ajax request could be triggered e.g. 200px before hitting the bottom - but I can't see there's a nice way of achieving this... Or am I missing something?

**Comment by hammertimedk** [comment]
I ended up hacking waypoints.js and just adding 500px - no other method worked in my use case:

```
  Waypoint.offsetAliases = {
    'bottom-in-view': function() {
      return this.context.innerHeight() - this.adapter.outerHeight() + 500
    },
    'right-in-view': function() {
      return this.context.innerWidth() - this.adapter.outerWidth()
    }
  }
```

It would be great if this could be a bit more flexible / configurable.

**Comment by imakewebthings** [comment]
@hammertimedk Offset is very flexible. You can pass it [any function](http://imakewebthings.com/waypoints/api/offset-option/#function) that returns a number. The alias that you have edited in your fork is just a shorthand for the function, but you can pass the function as the offset option directly without having to modify the alias list. Like so:

```js
new Waypoint.Infinite({
  element: $('.infinite-container')[0],
  offset: function() {
    return this.context.innerHeight() - this.adapter.outerHeight() + 500
  }
})
```

Or you could create your own alias in your own code, without modifying the waypoints file:

```js
Waypoint.offsetAliases['500-past-bottom'] = function() {
  return this.context.innerHeight() - this.adapter.outerHeight() + 500
}
new Waypoint.Infinite({
  element: $('.infinite-container')[0],
  offset: '500-past-bottom'
})
```

**Comment by td234** [comment]
I am so glad I found this. I was using a number to represent pixels expecting it to do the same thing. But it was rapidly loading each and every page all at once after I reached that point. It would be helpful to have this example in the docs. Thanks for a great script!!!
