### ISSUE TITLE
Can't use within iframe that's resized after load

### ISSUE THREAD

**Issue by zorborac** [imakewebthings/waypoints#408]
I am attempting to use waypoints within the context of an iframe that is resized after load so as to eliminate double scrollbars and such. 

Basically I a have an iframe that's 

``<iframe style="width: 800px; height: auto" src="source.html"></iframe>``

then quickly becomes

``<iframe style="width: 800px; height: 2400px" src="source.html"></iframe>``

The issue seems to be that viewport height seems to be reporting 2400px as soon as it's changed, triggering all of my waypoints at once, killing my nice effects. 

Any ideas? I'll have no access to the parent page in production.

**Comment by jaydenseric** [comment]
It's a good idea to trigger a recalculation of the waypoints any time the page height updates.

Try this:

```js
// Ensure waypoints correct after page load
$(window).on('load', function() {
	Waypoint.refreshAll();
});
```

I add this in all my projects. It seems to fix some weirdness when the waypoints are initialized and calculated on DOM ready before elements such as images load and cause the page height to grow.

**Comment by imakewebthings** [comment]
@zorborac Hard to say without a Fiddle/Codepen or link to a live site to see the issue.

**Comment by imakewebthings** [comment]
@zorborac Reopen/comment if you have anything further you can show.
