### ISSUE TITLE
Any way to debug Infinite request?

### ISSUE THREAD

**Issue by alancwoo** [imakewebthings/waypoints#409]
I'm trying to setup an infinite scroll, and see in the Network inspector that Infinite is indeed loading the 'next' page, but then nothing happens. The link disappears and nothing is appended. Is there any way to debug what is going on? Both the `onBeforePageLoad` and `onAfterPageLoad` functions are triggered.

Example page looks like:
````
<div id="wrapper">
  <article class="project">...</article>
</div>
<a class="next-project" href="#next-project">...</a>
````

JS:
````
var infinite = new Waypoint.Infinite({
  element: $('#wrapper'),
  items: $('article.project'),
  more: $('a.next-project')
});
````

Waypoints - 3.1.1
Waypoints Infinite Scroll Shortcut - 3.1.1

**Comment by alancwoo** [comment]
Well I discovered my stupid error, which is evident in the code above (wrapping the 'items' and 'more' selectors in $(...)).

**Comment by nicholasbulka** [comment]
Thanks for this! I was making the same mistake - I guess it's not a hard mistake to make.
