### ISSUE TITLE
Declarations for Typescript are missing

### ISSUE THREAD

**Issue by pligor** [imakewebthings/waypoints#410]
Congrats with the library!
We would like to use it with [Typescript](http://www.typescriptlang.org/) but we keep getting those annoying compile errors because we cannot find a declaration file of Waypoints inside https://github.com/borisyankov/DefinitelyTyped
Could you provide that? Thank you

**Comment by imakewebthings** [comment]
I will not be contributing those. Somebody who cares about Typescript and understands Waypoints enough to do it should make those contributions.

**Comment by dominikbulaj** [comment]
Hi, just an info - I've created typings for Waypoints based on [Waypoints API ](http://imakewebthings.com/waypoints/api/waypoint/). 
You can find it at: [https://github.com/dominikbulaj/WaypointsTypings](https://github.com/dominikbulaj/WaypointsTypings)

**Comment by evil-shrike** [comment]
@dominikbulaj Hi! Could you contribute the typing to https://github.com/DefinitelyTyped/DefinitelyTyped/? It's the place where people look for missing typings usually.
