### ISSUE TITLE
highlight navigation using waypoints.js

### ISSUE THREAD

**Issue by daghash** [imakewebthings/waypoints#411]
Hi,

I am using this code to highlight the current section in the navigation bar on one page website :

```js
var sections = $("section");
var navigation_links = $("#nav").find('a.smooth');
	
sections.waypoint({
  handler: function(direction) {
    var active_section = $(this);
    if (direction === "up") active_section = active_section.prev();
    var active_link = $('#nav a[href="#' + active_section.attr("id") + '"]');

    navigation_links.parent().removeClass("current");
    active_link.parent().addClass("current");
    console.log(sections);
    console.log(active_link);
    console.log(navigation_links);
    console.log(active_section);
  },
  offset: '30%'
});
```

But after scrolling to any section, I must resize the window to highlight the relative navigation link

Thanks

**Comment by stehefan** [comment]
Could you provide a HTML-Snippet of the page you're using? And do the log-commands give you the desired output?

BTW: you can use markdown for [syntax highlighting](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) ;-)

**Comment by imakewebthings** [comment]
@daghash A live link would be even better, either a JSFiddle/Codepen showing the issue or your own page.

**Comment by imakewebthings** [comment]
@daghash Closing until we have more information.
