### ISSUE TITLE
In Inview handler, "this" should refer to the Inview object instead of the wrapped Waypoint object

### ISSUE THREAD

**Issue by gabrielfin** [imakewebthings/waypoints#412]
When using Inview shortcut (and probably with Sticky and Infinite too), the handler function is called with `this` pointing to the individual waypoint object that triggered the event, instead of the Inview object to which it belongs.
Therefore, when you call this.destroy() from inside the handler, Waypoint.prototype.destroy is called instead of Inview.prototype.destroy and only 1 of the 4 waypoints is destroyed.

I think the solution would be to change line 72 of inview.js and pass `self` instead of `this` as the context.

**Comment by gabrielfin** [comment]
The suggested solution generates another issue.
When the element is already "in view", one of the sub-waypoints triggers its handler immediately, instead of waiting for the other sub-waypoints to be created. Therefore calling this.destroy() from the handler destroys only the waypoints that were created up to that point (i.e. the this.waypoints array might not yet contain all of the 4 sub-waypoints).

The only solution I can think of is to trigger the handler with a setTimeout, so that it is called after the Inview object has finished initializing. But that seems a bit hacky.

**Comment by imakewebthings** [comment]
@gabrielfin The multiple-initialization problem is one of the few outstanding known issues that I haven't come up with an elegant solution to.

I also agree Inview should trigger the handlers in the context of the outer Inview instance. Will mark this as an enhancement for a future version. Thank you!

**Comment by imakewebthings** [comment]
This is in a still-ongoing but soon-to-be-released 4.0.0 branch. And for those immediate triggers on freshly created, already passed waypoints, it happens that running those on the next animation frame solves a few different problems.
