### ISSUE TITLE
Safari error with jquery-pjax

### ISSUE THREAD

**Issue by jimzar** [imakewebthings/waypoints#414]
I use jquery-pjax for smoother experience and i activate the waypoint on the following events:
```
$(document).on 'ready pjax:success', ->
```

For some reason in chrome it works fine but in safari the triggerPoint is set to 0 and doesn't work properly.

**Comment by imakewebthings** [comment]
Can't help without a live example.

**Comment by imakewebthings** [comment]
@jimzar Closing until I have more information.
