### ISSUE TITLE
Inview refresh() method.

### ISSUE THREAD

**Issue by samburgers** [imakewebthings/waypoints#415]
Hi, 
Wondering if its possible to call refresh() on an Inview instance? If i add elements to the DOM, the waypoints of the Inview element get messed up. I can see that regular waypoints have a refresh() method, but not when using Inview.

Thanks.

**Comment by imakewebthings** [comment]
Regular waypoints do not have a `refresh` method. Contexts have a refresh method, and there is a shortcut to refresh everything, `Waypoint.refreshAll()`. You should use this.
