### ISSUE TITLE
(original) dropdown menu remains visible when scrolling past waypoint

### ISSUE THREAD

**Issue by pirco** [imakewebthings/waypoints#417]
I have a menu that's getting stuck via waypoints and works great but one of my menu items has a dropdown which, when scrolling past the waypoint where the menu gets stuck, remains visible. I figured this is best explained in a video: https://youtu.be/2Hw94Kg_178

**Comment by stehefan** [comment]
Could you please provide a working example of your code? It seems, like your menu get's cloned or whatnot. So a minimal example would be great if we should help you :-)

**Comment by pirco** [comment]
well, after more troubleshooting, I finally found the culprit... but please forgive me for not thinking that this line 
  li { line-height: 18px; margin-bottom: 12px; }
would be it!

I've set up two test pages: http://clients.piroc.com/ew/test.html shows the issue (hover over SHOP, then scroll up)
http://clients.piroc.com/ew/test2.html shows it's fixed by removing that CSS above (line 62)

now, I'd still like to know how THAT would affect the sub menu (I guess this is not a waypoints issue, sorry)

**Comment by stehefan** [comment]
Really strange and no Idea why this should happen - and it does not happen in the newest (dev) Firefox and Safari, so maybe it's a chrome-problem? Seems more like a rendering problem than something else.
