### ISSUE TITLE
Infinite scroll inside jquery dialog

### ISSUE THREAD

**Issue by manelis** [imakewebthings/waypoints#418]
Hello,

So I am trying to make the infinite scroll work inside a jquery dialog, however cant seem to find a way for it to work well. From what Ive tried I always reach one of two things, or the waypoint isnt fired and the infinite scroll doesnt work, or after 2 or 3 pages it goes completly crazy and loads a lot of the same pages reapetedly and doesnt stop. (like instead of 1,2,3,4,5,6,7 etc, it would do like 1,2,3,4,4,6,6,6,5,5,5,4,5,5,7 etc).

This is what a page looks like:

```
<div id='BattleReports'>
  <div class="head_box_vf">
    <h3>
      Previous Battles
    </h3>
  </div>

  <div id="battle_container">
    <div class="battle_entry">

        <!-- doesnt matter, content goes here -->

    </div>
  </div>

  <div id="pagination_battle">
        <a href="/land/html5_battle_index_page?turn=9" class="current  ">9</a>
        <a href="/land/html5_battle_index_page?turn=8" class="  next_page_battle">8</a>
        <a href="/land/html5_battle_index_page?turn=7" class="   ">7</a>
        <a href="/land/html5_battle_index_page?turn=6" class="   ">6</a>
        <a href="/land/html5_battle_index_page?turn=5" class="   ">5</a>
        <a href="/land/html5_battle_index_page?turn=4" class="   ">4</a>
        <a href="/land/html5_battle_index_page?turn=3" class="   ">3</a>
        <a href="/land/html5_battle_index_page?turn=2" class="   ">2</a>
        <a href="/land/html5_battle_index_page?turn=1" class="   ">1</a>
  </div>

  <script type="text/javascript">
      $( document ).ready(function() {
           infinite = new Waypoint.Infinite({
              element: $('#battle_container'),
              items: ".battle_entry",
              more: ".next_page_battle",
               context: $('#battle_index_content')
          });
      });
  </script>
</div>
```

With the code like this it will load a lot of the same pages as mentioned before.

#battle_index_content is the element of the dialog that has the overflow, and where the first page is added to with ajax.

Thank for any help, really running out of ideas.

**Comment by imakewebthings** [comment]
@manelis Very hard to say without seeing a live example, but one thing comes to mind, that `element` and `context` accept HTML elements, not jQuery objects. `document.getElementById('battle_container')` / `document.getElementById('battle_index_content')`.

**Comment by manelis** [comment]
Hello, I eventually solved the problem with another plugin. I tried with traditional javascript as you said but also didnt work.

Thank you for the help anyway.
