### ISSUE TITLE
Waypoint plugin does not fire on elements until i resize the window

### ISSUE THREAD

**Issue by daghash** [imakewebthings/waypoints#419]
I have one page website with html & body height 100%

i must resize the window to fire Waypoint on elements

**Comment by stehefan** [comment]
What exactly are you trying to do? I just tried a little [example](http://codepen.io/stehefan/pen/zGdvKv/) and it works perfectly well. For everything else, we would need an example from you I guess ;-)

**Comment by imakewebthings** [comment]
What @stehefan said. Need to see something to try debugging it.

**Comment by daghash** [comment]
Please find this example
https://goo.gl/yhsvwh
After loading the index page please scroll down to the next section 
it's supposed to trigger the counters but this will not happen until you re-size the window

Thanks

**Comment by stehefan** [comment]
As I see it, you instantiated the waypoint in the wrong way. I used your code to create this [pen](http://codepen.io/stehefan/pen/qdpXVR) and it works, if you use the context option as I used it there. No problems on my side so far.

I guess, your third parameter to the waypoint-function just got uninterpreted, because it is not supposed to have 3 parameters. The options are combined in one parameter-object, not separate objects.

**Comment by daghash** [comment]
You are right
Now it's ok
Thank you very much for your help

**Comment by makc9I** [comment]
have the same problem, tried to add parameter context: $("body"), but after that waypoint completly haven't work.
If i dont use parameter contex: , it work only after window resize.

**Comment by makc9I** [comment]
still have this problem...
[http://sandbox.maximshadrin.ru/aquanomika/](http://sandbox.maximshadrin.ru/aquanomika/)

**Comment by abdokouta** [comment]
[Data.zip](https://github.com/imakewebthings/waypoints/files/1196089/Data.zip)
i have an issue with waypoint is it works only while page load after that it's like stucking untill i resize the screen here is my code and i uploaded my css and js files and that code include in file called "js_composer_front.min.js"
`"function"!=typeof window.vc_waypoints&&(window.vc_waypoints=function() {
    "undefined"!=typeof jQuery.fn.waypoint&&jQuery(".wpb_animate_when_almost_visible:not(.wpb_start_animation)").waypoint(function() {
        jQuery(this).addClass("wpb_start_animation animated")
    }
    ,
    {
        offset: "85%"
    }
    )
}`

**Comment by psalmskalu** [comment]
Please I am having this issue now. I wish the link to the pen http://codepen.io/stehefan/pen/qdpXVR which apparently has the solution, still works. Please how do you solve this. it only works when I resize the window. is this a bug with Waypoints

here is my code:

```
<script>
     
        var infinite = new Waypoint.Infinite({
            
          element: $('.posts_panel')[0],
          handler: function(direction) {
            notify('Waypoint triggered in ' + direction + ' direction');                        
            
         },
         offset: 'bottom-in-view',
         //context: $('#scroll-space'),
          onBeforePageLoad: function () {        
            $('.loading').show();
            
          },
          onAfterPageLoad: function ($items) {            
            $('.loading').hide();
            Waypoint.refreshAll();
          }
        });

    
        
      </script>
```
