### ISSUE TITLE
jQuery build - switch context via callback?

### ISSUE THREAD

**Issue by CBarbs** [imakewebthings/waypoints#420]
Hi,

I am currently using the jQuery build for waypoints.

What I would like to do, is switch the context selector for my waypoints via a callback. Is it possible? Or will I need to use the regular build?

Thanks,
Craig

**Comment by imakewebthings** [comment]
@CBarbs Interesting. Would you be willing to share exactly the use case or what you're trying to get done?

**Comment by imakewebthings** [comment]
If you have more info let me know here and I can reopen this.
