### ISSUE TITLE
commonJS modules

### ISSUE THREAD

**Issue by hellbeast92** [imakewebthings/waypoints#421]
Hello, do you plan to wrap the code into commonJS modules and not to store data in a window?
I would like to connect a Waypoint at each location where it is used, not in the head of the file, like jquery.

**Comment by cameronjroe** [comment]
+1 I'd like to use waypoints from Browserify and currently it doesn't have a `main` attribute defined in the package.json.

**Comment by imakewebthings** [comment]
No plans. Used to provide this library as a module and it was more pain by people trying to use the shortcuts than it was worth. Please shim or maintain a fork that wraps in the way you wish.
