### ISSUE TITLE
Infinite not working on overflow container

### ISSUE THREAD

**Issue by Jordan4jc** [imakewebthings/waypoints#422]
I have set up a jsbin with a basic example of what I have

http://jsbin.com/putawoboki/edit?html,css,js,output

There is a navigation on the left side that is fixed to the #content area is the part that is scrollable.

**Comment by stehefan** [comment]
You forgot to set the context. Without this, the script does not know when the 'bottom-in-view' is fulfilled and does not fire. Look at [this example](http://codepen.io/stehefan/pen/qdpXym/).

**Comment by imakewebthings** [comment]
Yes, what @stehefan said, you need the [context option](http://imakewebthings.com/waypoints/api/context-option/).
