### ISSUE TITLE
Firefox uses bottom of page instead of top

### ISSUE THREAD

**Issue by cyllu2** [imakewebthings/waypoints#424]
Granted, Firefox is the shittiest browser known to man, but unfortunately one has to build for everything, so it was disheartening to discover that although Chrome, Opera, Safari, etc. uses the top of the page to match against the waypoint, Firefox uses the bottom!

I'm curious as to why this is and why this isn't documented anywhere or even reported as an issue here before?

**Comment by imakewebthings** [comment]
Would you be willing to provide a link to something that demonstrates this behavior you see in Firefox?  It seems something has caused you great pain and frustration.



—

**Comment by imakewebthings** [comment]
@cyllu2 I hope everything is well with you. Closing this.

**Comment by jdx10** [comment]
I can confirm this issue with Firefox. I can't give you a link, it's on localhost.
