### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by sebastianthomas** [imakewebthings/waypoints#425]
Hey I think there might be a build problem or a typo in the built code in the Zepto waypoints js. 
I downloaded this
https://github.com/imakewebthings/waypoints/blob/master/lib/zepto.waypoints.js#L7

and running that got this error `Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function(anonymous function)`

But looking at the minned version the first character is `!`
https://github.com/imakewebthings/waypoints/blob/master/lib/zepto.waypoints.min.js#L7

which is missing on the unminned version. 

Added the `!` and it all works.

**Comment by imakewebthings** [comment]
@sebastianthomas Would you be able to show me a page with this error. I created a blank page with nothing but Zepto 1.1.6 and zepto.waypoints.js and saw no error.

**Comment by imakewebthings** [comment]
@sebastianthomas If you have more info let me know and I can reopen this.
