### ISSUE TITLE
Using version v2.0.4 and animate.css in WordPress.

### ISSUE THREAD

**Issue by paaljoachim** [imakewebthings/waypoints#428]
Hi

-- Question how do I use the newest version of waypoints instead of an older version? Getting that to work in WordPress as I have done with the older version.

I have been looking at how the following WordPress Genesis theme uses waypoints 2.0.4 and animate.css
http://themes.janhoek.com/genesis-themes/jano/  

I downloaded the theme and the files and began experimenting. I am then using the older waypoints version and the following code in a waypoints-init.js file.

'jQuery(function($) {

	$('#front-page-1 h1').waypoint(function() {
		$(this).toggleClass( 'animated bounceInDown' );
	},
	{
		offset: '100%',
		// triggerOnce: true
	});
	
	$('#front-page-1 img').waypoint(function() {
		$(this).toggleClass( 'animated fadeInUp' );
	},
	{
		offset: '90%',
		// triggerOnce: true
	});
	
	$('#front-page-3 p').waypoint(function() {
		$(this).toggleClass( 'animated fadeInUp' );
	},
	{
		offset: '90%',
		// triggerOnce: true
	});
});'

In the functions.php file I use:

//* Enqueue Parallax on non handhelds i.e., desktops, laptops etc. and not on tablets and mobiles
add_action( 'wp_enqueue_scripts', 'enqueue_animate' );
function enqueue_animate() {
	// Source: http://daneden.github.io/animate.css/
	wp_enqueue_style( 'animate', get_stylesheet_directory_uri() . '/css/animate.css' );
		wp_enqueue_script( 'waypoints', get_stylesheet_directory_uri() . '/js/waypoints.min.js', array( 'jquery' ), '1.0.0' );
	wp_enqueue_script( 'waypoints-init', get_stylesheet_directory_uri() .'/js/waypoints-init.js' , array( 'jquery', 'waypoints' ), '1.0.0' );
}

I am getting the above to work correctly in the Parallex theme I am using in WordPress.

The questions:
Which file replaces the older waypoinst.min.js file? 
How do I get it to work correctly?

Step by step would be great. Easy to follow tips and tricks on using waypoints is also helpful.

Thanks!

Btw
I plan on creating a tutorial that I will add to this site (any help I can get along the way really does help):
http://easywebdesigntutorials.com/

**Comment by imakewebthings** [comment]
@paaljoachim What have you tried already?

**Comment by paaljoachim** [comment]
Downloaded the zip file from this Github repo.
Copied over jquery.waypoints.min.js -> js folder inside the parallex theme I am using.
Adjusted the following line in the functions.php file to be: wp_enqueue_script( 'waypoints', get_stylesheet_directory_uri() . '/js/jquery.waypoints.min.js', array( 'jquery' ), '1.0.0' );

Tested the theme. None of the effects worked. Switched back to the older file that I used waypoints.min.js (v2.0.4)  and it worked again. Renamed the old file and renamed the new file to be waypoints.min.js to see if that would help but no change. 

I am stuck as the new file jquery.waypoints.min.js is not working with the code I am using.

**Comment by imakewebthings** [comment]
The major version change from 2.x to 3.x introduced breaking changes to the API of Waypoints. That's what makes it a major version bump in [semver](http://semver.org/). You **almost certainly** will have to make code changes to your theme to use the new API.

**Comment by imakewebthings** [comment]
A hint: You'll want to use `this.element` to refer to the DOM node now instead of `this`

**Comment by paaljoachim** [comment]
Hey Caleb

I have figured out that these codes work:

'jQuery(function($) {
	$('#front-page-3').waypoint(function() {
			$('#front-page-3 h1').toggleClass( 'animated flipInX' );
			$('#front-page-3 img').toggleClass('animated fadeInUp') ;
			$('#front-page-3 p').toggleClass('animated fadeInUp');
		},
		{
			offset: '100%',
			triggerOnce: true
		});
		
		$('.front-page-1 h1').addClass('animated fadeInDown');
});'

How do I add a staggered animation to the #front-page-3 p class?
How do I also get the front-page-3 effects to show up gradually as I scroll through them?
What is the code that I add into the above code and where to I add it?

Thanks!

**Comment by imakewebthings** [comment]
Those are great questions that I will not be answering.



​


On Thursday, Aug 13, 2015 at 5:43 PM, Paal Joachim Romdahl <notifications@github.com>, wrote:

Hey Caleb


I have figured out that these codes work:


'jQuery(function($) {

    $('#front-page-3').waypoint(function() {

            $('#front-page-3 h1').toggleClass( 'animated flipInX' );

            $('#front-page-3 img').toggleClass('animated fadeInUp') ;

            $('#front-page-3 p').toggleClass('animated fadeInUp');

        },

        {

            offset: '100%',

            triggerOnce: true

        });


    $('.front-page-1 h1').addClass('animated fadeInDown');


});'


How do I add a staggered animation to the #front-page-3 p class?

How do I also get the front-page-3 effects to show up gradually as I scroll through them?

What is the code that I add into the above code and where to I add it?


Thanks!

**Comment by paaljoachim** [comment]
Ok thats fair. I will then figure it out and post what I find here.
