### ISSUE TITLE
Cannot find module 'waypoints' by npm installed

### ISSUE THREAD

**Issue by smallma** [imakewebthings/waypoints#431]
Hi all,
  I installed waypoints and require in js, but there is a error as 'Cannot find module 'waypoints'. I check package.json and not found main option. Is there anyone can solve this? Thanks

**Comment by imakewebthings** [comment]
I have no foreseeable plans to make Waypoints a CommonJS or AMD module. Please [shim](https://github.com/thlorenz/browserify-shim) until somebody can convince me that there's a way to expose the multiple core library builds + the shortcuts without causing myself and others pain.

**Comment by kentmw** [comment]
@imakewebthings, if I'm not mistaken, your project exports one thing, Waypoint. Can't you wrap that object in a UMD block?

**Comment by kentmw** [comment]
For now, people wanting to use this with Browserify can do:
```
require('waypoints/lib/jquery.waypoints');
```
and then use window.Waypoint
