### ISSUE TITLE
Waypoint Handler being triggered on DOM Replacement

### ISSUE THREAD

**Issue by meowsus** [imakewebthings/waypoints#432]
I just wanted to report this to try to see if you knew why this might be happening. 

Consider the layout

Page Aside | Page Content
--------------- | -------------------
Ajax Filter 1 | Row of Products
Ajax Filter 2 | 
Ajax Filter 3 | 

I have a waypoint set to the row of products, offset is 50%. When the row is in the horizontal center of the page, then next Row of Products is loaded, and so on, until a threshold is hit.

When I filter the products the entire layout (represented by the table, above) is replaced with the result of the ajax request. For example, say the table is `.page-layout`. The ajax request grabs the next page, filters through it's DOM, pulls out the `.page-layout` from the response, and replaces the current `.page-layout` with the new `.page-layout`.

At the exact moment of the replacement, a waypoint is triggered, even though the page does not scroll what-so-ever.

How I got around it is by globally disabling all of the waypoints just before the replacement, then re-enabling them after the content has been replaced. 

The reason I'm bringing this up is that it seems more like a bug to me. If the element that has a waypoint handler bound to it is removed from the DOM, why would that trigger a waypoint event?

**Comment by imakewebthings** [comment]
@meowsus When you are doing the replacement, it is up to you to [destroy](http://imakewebthings.com/waypoints/api/destroy/) the existing waypoints on the soon-to-be-toast DOM elements.

**Comment by imakewebthings** [comment]
Closing this per above comment.

A little more detail:

Waypoints are not automatically destroyed when their underlying element is removed from the DOM, nor do they perform checks that their element is still in the DOM before triggering.

When you add your next page and its batch of Waypoints, that triggers a `refresh` where all of the triggerPoints are calculated. Even the triggerPoints of those elements that aren't in the DOM. I believe those elements will **say** they are at the page coordinates of 0,0. That move in location, which crosses the current scroll point, would trigger the handler in the up direction.
