### ISSUE TITLE
Waypoints don't trigger with html height: 100%

### ISSUE THREAD

**Issue by khalwat** [imakewebthings/waypoints#438]
I'm having an issue similar to this:

http://stackoverflow.com/questions/19816007/jquery-waypoints-context-not-working-in-safari-or-chrome

Essentially, I'm doing a full screen video, and to get it to work using this technique:

http://demosthenes.info/blog/777/Create-Fullscreen-HTML5-Page-Background-Video

...I need to set the css attribute:

    html,body {
    width: 100%;
    height: 100%;
    }

The problem is, with this attribute in the CSS, none of my waypoints trigger.  They work if I do something gross like this:

    $('body').on('scroll', function(){Waypoint.refreshAll();});

...and they also work (but then the full screen video doesn't work) if I remove the height: 100% from the  site CSS.

So it appears that somehow, setting height: 100% on html,body causes Waypoints to break.  How can I get them to get along?

**Comment by landitus** [comment]
I have the same issue. Removing the 100% height on html,body solves it. Is this something that should be documented or fixed?

**Comment by katybarlowe** [comment]
I have this issue as well - but I need height:100% in order for a fixed position header to work correctly.  Please resolve.

**Comment by stehefan** [comment]
I'm not quite sure here, but I guess you have to adjust your [context](http://imakewebthings.com/waypoints/api/context-option/) to your body instead of the default. Just a guess, but worth a try I guess :-)

**Comment by imakewebthings** [comment]
@khalwat @katybarlowe Do you have a page I could look at? Are you also using `overflow:scroll` on either the body or the html element?

**Comment by Ivan-Perez** [comment]
Adjusting the `context` to `document.body` fixes the issue for me.

**Comment by zhengyinxi** [comment]
waypoint.triggerPoint = Math.floor(elementOffset + contextModifier - adjustment)

jquery offset function does not necessarily return integer when element height is set percentage or auto (eg. 100%), but jquery scrollTop function usually return integer, so there is still some chance when trigger point height is bigger than scroll height even when scroll is at bottom(eg. trigger point position is {top:1565.01},while scrollTop() returns 1565 )

**Comment by imakewebthings** [comment]
If anybody cares to provide an example I can reopen.

**Comment by semihozbag** [comment]
Hello there, here is the issue;

http://trtevsinemasi.gablemonroeclift.com

First, enter the site and wait till the video ends. Or manually forward the video to the end (player has a callback for the header).  The start scrolling you'll see an effect with the section headers.

Then, scroll to the middle of the page and refresh. Wait for video to the end and then scroll again. You'll see a difference on the effect. triggerPoint is changed, not the given offset.

i hope i have told the problem with my bad english
