### ISSUE TITLE
noframework adapter outerHeight  is incorrect if the element has a scale transform applied

### ISSUE THREAD

**Issue by tangent405** [imakewebthings/waypoints#439]
It appears that getBoundingClientRect() is used for the offset but not for outerHeight and outerWidth. This means the following example won't work correctly if myelement has a scale transform applied:

    var waypoint = new Waypoint({
      element: myelement,
      handler: function() {
        console.log('fired');
      },
      offset: 'bottom-in-view'
    });

http://jsfiddle.net/b49wzjh0/1/

Note: I believe innerWidth likely has the same problem. Should innerWidth and innerHeight include the border? (I believe jquery does not, but getBoundingClientRect would, so the fix might require figuring out the actual transform matrix so you can subtract the border).

I am happy to submit a pull request with a potential fix if you would like.

**Comment by imakewebthings** [comment]
This is how it works with jQuery too: http://jsfiddle.net/b49wzjh0/3/
