### ISSUE TITLE
Offset is wrong on calculating height of fixed element

### ISSUE THREAD

**Issue by janhartmann** [imakewebthings/waypoints#447]
First of all, I am not sure this is a bug or the way I am using this library.

On our page we have a `top` , a `header` and underneath the `content` of the page.

When the document is loading, I am applying a "fixed" CSS class to the `header` which removes some elements and adjusting some padding for the `header`. I then get the height of the fixed `header`, save it and remove the "fixed" CSS class again. The content of the `header` is dynamic, I do not know the height before hand.

What I am now trying to do is that when you scroll down the page I am looking for the moment when the visible part of the `header` is the same height of the fixed height of the header. Once I reach this point I switch over to the fixed version of the `header` so there is a seamless transition from the big header to the fixed, much smaller header and which is now stuck to the top.

But I can not seem to make it completely seamless. There is a gap which annoys me. Is there any way I can achieve the above?

I have created a JSFiddle for the experiment I am working with: http://jsfiddle.net/cns9v6ay/3/

**Comment by stehefan** [comment]
Hej,

you did some false assumptions and calculations I guess. The following code works:

```javascript
var getFixedHeight = function(element) {
    try {
			element.addClass("fixed");
			return element.outerHeight();
	} finally {
			element.removeClass("fixed");
	}
}

var header = $("#header");
var height = header.outerHeight();
var fixedHeight = getFixedHeight(header);
var content = header.next("div");

header.waypoint({
	handler: function(direction) {
		if (direction == "down") {
			header.toggleClass("fixed");
			content.css("padding-top", height + "px");
		} else {
			header.toggleClass("fixed");
			content.css("padding-top", "0px");
		}
	},
	offset: function() {
		return -(height - fixedHeight)
	}
});
```

You want the negative offset to be the difference between the small and the tall header to be used correctly. And without using .outerHeight() you don't count in the padding and stuff, so your height was not calculated correctly.

Hope this helped :)

**Comment by janhartmann** [comment]
Oh, thank you so much. Been starring at this for a while now. Works exactly like I imagined! 

I'll close this and thanks again!
