### ISSUE TITLE
Creating Inview with element above page invokes all callbacks

### ISSUE THREAD

**Issue by kentmw** [imakewebthings/waypoints#449]
Creating an inview shortcut with the element already above the viewport, will trigger enter, entered, exit and exited.

**Comment by imakewebthings** [comment]
@kentmw Yep.

**Comment by kentmw** [comment]
Fair question. If you have a list of items you expect to read from top to
bottom and you're adding to the top, maybe you don't mind to have it run
through the life cycle quickly, but the problem is that whatever element
you are attaching to the dom above the scroll level never entered the
viewport. What is the enter/entered event mean then? To me it meant the
element entered the viewport and so having fired these events was an error.
Maybe to you it means the viewport is lower than the element. Perhaps the
documentation needs to change. Ultimately, for me, having callbacks that
alert users that something entered the viewport started blasting confusing
messages to the user that he has never seen.

**Comment by imakewebthings** [comment]
I can see how being deep linked into the Inview doc page could be confusing in that way. My apologies. It did appear to have the desired effect in the end of showing you what would **actually** happen if you used Inview and jumped around the page. You understand perfectly that it will fire those callbacks in that order, and hopefully you'll write your handlers in a way that these things fired in that order end up doing what you need to do.

About your problem at hand, of wanting to ensure that the user "sees" the item in the viewport, I suggest using timers like so:

```js
var timer
var element = document.getElementById('thing')

function enteringHandler () {
  window.alert('entering')
}

new Waypoint.Inview({
  element: element,
  entering: function () {
    timer = window.setTimeout(enteringHandler, 100)
  },
  exited: function () {
    window.clearTimeout(timer)
  }
})
```

A big jump would trigger the `exited` right after the `entered` and it would be cleared before executing.

**Comment by imakewebthings** [comment]
Closing this, recommending timers in userland for now.
