### ISSUE TITLE
Trigger waypoints with css-transform?

### ISSUE THREAD

**Issue by lucasdidthis** [imakewebthings/waypoints#451]
Hej!

Is there a way to trigger waypoints when an Element enters the viewport with css-transform?

I can't find a solution in the Guides or the API, but it would be awesome, because I want to combine waypoints with a modern Slideshow.

Thanks & Kind Regards,
Lucas

**Comment by imakewebthings** [comment]
@lucasdidthis I don't have a great answer for you. "Probably not" is the best I can do for now. Waypoints is very tied to the scroll and resize events right now. It may be interesting to play with abstracting out the generator of trigger checks but I'm not likely to explore that any time soon.
