### ISSUE TITLE
waypoint, offset value from the data attribute

### ISSUE THREAD

**Issue by thirumani02** [imakewebthings/waypoints#452]
I am struggling the get the value from my HTML element's data attributes. For each element, i want to use different offset so i planned to get the offset value from the data attribute.

here is my code

```html
<div class="waypoint" data-waypoint-offset="50%" >
// my code
</div>
```

And this my script

```js
$('.waypoint').waypoint(function() {
    $(this.element).addClass('animated');
}, {
    triggerOnce: true,
    offset: function() {
       return $(this.element).data('waypoint-offset');
   }
})
```

But class "animated" added only after element reaches the top(offset 0).

I also tried

```js
return $(this).data('waypoint-offset');
```

But doesn't help.

thank you

**Comment by imakewebthings** [comment]
@thirumani02 In the "Possible Values" section of the [offset option documentation](http://imakewebthings.com/waypoints/api/offset-option/) you'll see this under "function":

> The function must return a number of pixels, as if you were using a number offset. The function is re-evaluated whenever a trigger point is recalculated, allowing for changes in layout.

You can't use a function offset to return a % offset string. It must return a number.

You can still do what you want though by not using a function offset!

```js
$('.waypoint').each(function(el) {
  var $element = $(el);

  $element.waypoint(function() {
    $(this.element).addClass('animated');
    this.destroy();
  }, {
    offset: $element.data('waypoint-offset')
  });
});
```

Note that I've also converted your `triggerOnce` to calling `destroy` at the end of the handler. `triggerOnce` was removed in 3.0.0.

**Comment by thirumani02** [comment]
Hello,

This function leads the following error 
<pre>Uncaught TypeError: Cannot read property 'top' of undefined </pre>

**Comment by imakewebthings** [comment]
@thirumani02 It's been so long since I've jQuery'd that I forgot how its `each` works. `el` was the index and not the element in my example previously. I've updated the comment above.

**Comment by thirumani02** [comment]
Wow. its working!  Great Thanks :-)
