### ISSUE TITLE
Waypoints.enableAll() big delay

### ISSUE THREAD

**Issue by quadri** [imakewebthings/waypoints#454]
Hi.

I have web page with about 600 waypoints. And I get a big delay over 15 seconds on Waypoints.enableAll() call. I'm using noframework.waypoints.js on mobile device.
I looked at Waypoints code and saw that on each enable() call there are this.context.refresh() call.
Docs says "This method forces a recalculation of the trigger point for every waypoint in this context", so  if I understand correctly I get 600*600 recalculating calls?

I have made 2 changes:
1) remove this.context.refresh() call from Waypoint.prototype.enable, result:
  Waypoint.prototype.enable = function() {
    this.enabled = true
    return this
  }

2) add refreshAll() to enableAll() method, result:
  Waypoint.enableAll = function() {
    Waypoint.invokeAll('enable')
    Waypoint.Context.refreshAll();
  }

It works for me much better, delay is almost insensible.
But I want ask you about some possible sideeffects caused by these changes.

Thank you

**Comment by imakewebthings** [comment]
Thanks for bringing this to my attention @quadri. The side effect you'll get from your change is calling `enable` on a single Waypoint could maybe end with the triggerPoint for that Waypoint being wrong, perhaps if the layout of the page changed due to user resizing between the time it was disabled and enabled.

I should be able to get a change in the next release that takes care of the performance problem without endangering any triggerPoints.

**Comment by tombueng** [comment]
Inview(options) calls createWaypoints, wich leads to the same issue. context.refresh called for any new waypoint.

**Comment by adamgins** [comment]
Hi, I seem to have a similar problem. Just wondering if there's a best practice for having many waypoints? I am getting slowness when I have approx 20 of them and I use `context`. Without `context` set it seems to be pretty fast.

I am currently initializing each waypoint separately vs one jquery call. 

Any hints pls?

**Comment by imakewebthings** [comment]
Fixed in the 4.0.1 release.

@adamgins Like a lot of things, it depends. Would need to see your code. In general there's no one way to make Waypoints that is better or worse than another.
