### ISSUE TITLE
Delay or queue for waypoints

### ISSUE THREAD

**Issue by inoks** [imakewebthings/waypoints#455]
Let say i have 100+ waypoints available on my page.
When user click on link with anchor, which linked at the end of the page - all of the waypoints are triggered.
Is any way to queue with some delay so in that case only last waypoint will be triggered?

**Comment by shellscape** [comment]
@inoks a throttle or debounce lib used on your callback should help with that.

**Comment by inoks** [comment]
@shellscape Cool, thanks!

**Comment by imakewebthings** [comment]
@inoks @shellscape There's that, or the [continuous option](http://imakewebthings.com/waypoints/api/continuous-option/) was created for just this occasion. Setting it to `false` makes it so that during any single scroll check multiple waypoints are passed, only the last one is triggered.

**Comment by shellscape** [comment]
@imakewebthings that brings up an interesting scenario - say I have 30 items on a page, 6 of which are in the viewport and visible at any given time. If a user scrolls down to the bottom, he exposes the last six items in the page. If only the last waypoint with continuous is triggered, how would one know that the previous 5 were also visible, assuming that each item has a waypoint.
