### ISSUE TITLE
Way to trigger no framework waypoint on classes?

### ISSUE THREAD

**Issue by chris480** [imakewebthings/waypoints#459]
There doesn't seem to a be a way to trigger waypoint on class out of the box.  Am I mistaken? If not, this would be a great feature instead of triggering only by IDs.

**Comment by imakewebthings** [comment]
The `element` option of the noframework build doesn't even take IDs. It takes an [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element). You're probably referring to my liberal use of `document.getElementById` in the docs. That method returns a single element. `document.getElementsByClassName` will return you a list of all elements with a given class name, then you can loop over that list and create waypoints on each of them. I have an example of this on the [continuous option page](http://imakewebthings.com/waypoints/api/continuous-option/). Good luck!
