### ISSUE TITLE
Uncaught TypeError: r.default is not a function

### ISSUE THREAD

**Issue by jarodtaylor** [imakewebthings/waypoints#460]
I'm trying to use the noframework version of Waypoints in a project using babel and es6 modules. Unfortunately I cannot seem to get it to work.

I have a `main.js` file that calls for the import:

```
import Waypoint from '../../node_modules/waypoints/lib/noframework.waypoints.min.js';
```

I have to import it this way unless I add `"main" : "./lib/noframework.waypoints.min.js"` to your `package.json` file, which I want to avoid. Not a big deal.

Okay, so when I do this and then add a simple test instance of it in my same `main.js` file:

```
const waypoint = new Waypoint({
  element: document.querySelector('.logo-icon-hero'),
  handler() {
    console.log('found it!');
  }
});
```

I get this error in Chrome:

```
Uncaught TypeError: r.default is not a function
````

At first, I thought maybe the file wasn't actually being imported into my `main.js` file, but when I view source I see it's in the file. In fact, I can run `new Waypoint({..})` just fine in the Chrome console.

**Comment by jarodtaylor** [comment]
It looks like the only solution at the moment is to use what Peter used in his pull request: #426

**Comment by imakewebthings** [comment]
Closing this as dup of #458. Please see discussion there and https://github.com/imakewebthings/waypoints/issues/458#issuecomment-151735949.
