### ISSUE TITLE
Disable support for Sticky shortcut

### ISSUE THREAD

**Issue by jackmcdade** [imakewebthings/waypoints#462]
I'm using Vue.js directives to dynamically bind the Waypoint.Sticky class and it automatically triggers the "stuck" behavior no matter what I do. Is there a way to support the `.disable()` method to prevent that behavior?

**Comment by imakewebthings** [comment]
@jackmcdade Can you show me?

**Comment by imakewebthings** [comment]
@jackmcdade I'll reopen if you have more info.
