### ISSUE TITLE
Waypoint.refreshAll() doesn't recalculate offset with function (Chrome, Safari)

### ISSUE THREAD

**Issue by cupcakedream** [imakewebthings/waypoints#464]
Hey there,
First, thanks for the awesome plugin. I have a function as an offset for my waypoints instance, so the offset is dynamically created depending on the height of a related element. I'm calling `Waypoint.refreshAll` when the height of the related element changes, and the issue I'm having is, the offset doesn't get recalculated when I call the function. I've tried `refreshAll` directly from the javascript console as well, after making sure the height on the trigger element has changed in the dom, but still no luck. When I resize my browser though, the offset gets recalculated correctly. I'm using Chrome & Safari to test. Is the resize trigger doing anything else or maybe I'm missing something?

**Comment by vannguyen87** [comment]
I also encountered similar problems.
Thanks for any assistance!

**Comment by imakewebthings** [comment]
@cupcakedream @vannguyen87 Thanks for the report. Do either of you have an example I could see? Changing element heights and running `refreshAll` in the console on my docs pages work as expected.

**Comment by imakewebthings** [comment]
@cupcakedream @vannguyen87 If y'all could provide an example that shows this I will reopen, but closing this as cannot reproduce for now.
