### ISSUE TITLE
Incorrect detection when using a sticky footer

### ISSUE THREAD

**Issue by migig** [imakewebthings/waypoints#465]
My footer is "sticky" with `position:absolute` and `bottom:0px`. I'm not referring to the sticky feature in this library.

I want to detect when the user scrolls to the very bottom of the page, so my waypoint is:

    new Waypoint({
      element: document.body,
      offset: "-100%",                               // I also tried "bottom-in-view"
      handler: function (direction) { /* ... */ }
    });

However due to the absolute positioning, the waypoint is triggered a lot before the actual bottom of the page. Is there some way to correct for this?

**Comment by imakewebthings** [comment]
@migig Using `body` as the element wont do what you hope here. The answer also depends on your CSS and HTML, but here's a try at it:

If you have a wrapper around all of your content on the page this get's really easy:

```js
new Waypoint({
  element: document.getElementById('page-wrapper'),
  offset: 'bottom-in-view',
  handler: function (direction) { /* ... */ }
})
```

If you don't have a wrapper, the CSS gets fussier and there may be cross browser issues with various height methods, but it would look something like this:

```js
new Waypoint({
element: window,
offset: function () {
  return -document.body.scrollHeight + document.body.clientHeight
},
handler: function (direction) { /* ... */ }
```
