### ISSUE TITLE
Quick check if is inview?

### ISSUE THREAD

**Issue by katerlouis** [imakewebthings/waypoints#468]
Hey folks,
I need to figure out elsewhere in the code if my element is inview or not. 
Is there some way to ask the inview variable if the element is currently in view?

something like:

var inview = new Waypoint.Inview({ ...

if (inview.isInview) { }

A workaround would be to change a var-state inside the enter and exited events, but that's pretty inconvenient for me. Just asking the object would be a huge benefit for me. Any ideas how to implement this?

Thanks! 
Louis

**Comment by shellscape** [comment]
:+1: for this feature. Our use case is tracking when an item comes into view, and adding a delay to double check that the user spent at least n milliseconds with the item still in view.

**Comment by imakewebthings** [comment]
@katerlouis @shellscape 

Set a data flag (or class if you wish) on the element in the handler.

```js
onEnter: function () {
  this.element.setAttribute('data-inview', true)
},
onExit: function () {
  this.element.removeAttribute('data-inview')
}

/* ... */

thatElement.getAttribute('data-inview')
```

**Comment by shellscape** [comment]
Outstanding. Thanks for adding that @imakewebthings :+1:

**Comment by shellscape** [comment]
@imakewebthings finally just getting around to adding this to our code... I don't see the use or reference of `enter` or `exit` anywhere in the distributed code for the latest release. Please advise?

**Comment by imakewebthings** [comment]
https://github.com/imakewebthings/waypoints/blob/master/lib/shortcuts/inview.js

http://imakewebthings.com/waypoints/shortcuts/inview/

**Comment by shellscape** [comment]
@imakewebthings total brain fart over there, thanks much.
