### ISSUE TITLE
iOs momentum scrolling

### ISSUE THREAD

**Issue by lisfox1** [imakewebthings/waypoints#469]
When implement waypoint code from below there is a problem when doing a momentum (quick) scroll. Even that the code from bellow should only fire if its 60px from the element its fire on a momentum scroll too.   
Is this any works around it?

```
var $stickyMainSearch = $('#home-page .main-vrm-search').first(),
    
    
if ( $stickyMainSearch.length > 0 ) {
        
	var wayRaiseSearch = new Waypoint({
		element: $stickyMainSearch[0],
		handler: function(direction){
			var searchOverlapsBrand = ( $stickyMainSearch.offset().left < ($namedBrandLogo.offset().left + $namedBrandLogo.width()));
			var scrollingDown = (direction === "down");
                
			$namedBrandLogo.toggleClass('hideOffPage',(scrollingDown && searchOverlapsBrand));
			$namedBrandLogo.toggleClass('displayInHeader', !$namedBrandLogo.hasClass('hideOffPage'));
		
			$stickyMainSearch.toggleClass('displayInHeader',scrollingDown);
			$stickyMainSearch.toggleClass('displayInBody', !$stickyMainSearch.hasClass('displayInHeader'));
                
            },
            offset: function(){
               return 60;
		}
	});
}
```

**Comment by johndevor** [comment]
Not sure if related, but I'm also having issues with waypoints not getting triggered on mobile.

**Comment by imakewebthings** [comment]
@lisfox1 @johndevor Up until recently, Safari for iOS would only fire a scroll event once at the end of momentum scrolling, and there were no other intermediate events fired to hook into. The newer JS engine for Safari does fire multiple scroll events as you scroll but if you're using something that still runs on the old JS engine (like a UIWebView I think, but I'm not an iOS dev so I encourage you to dig further on your own) you get the old behavior.
