### ISSUE TITLE
Handler getting triggered twice upon page reload

### ISSUE THREAD

**Issue by janwidmer** [imakewebthings/waypoints#470]
Hi There, 
I am having a weird behavior when I use waypoints to build a sticky Element. I am using the "noframework" version 4.0.0. (I cannot use the jquery version and shortcut because I have a legacy jquery version and cannot update) When I scroll manually to the position of the sticky element, everything works as it should. The Problem occurs, when the scroll position is somewhere down the page and I refresh the page. Chrome then jumps to the scroll position of before the refresh. So far so good. After the refresh, the Waypoints handler is getting triggered twice, first with direction = "down" and second with direction = "up". This causes my sticky element to first getting the "stuck" class and the immediately getting it removed and therefore my element is not sticky even though, the scroll position is somewhere down the page.

It seems, that the handler is getting triggered twice with both directions after a page refresh and the scroll position != top of the page.

My Waypoints configuration:

```
var shareButtons = document.getElementById('share-buttons');
        new Waypoint({
            element: shareButtons,
            handler: function(direction) {
                if(direction === 'down'){
                    jQuery(this.element).addClass('stuck');
                }
                else{
                    jQuery(this.element).removeClass('stuck');
                }
            },
            offset: 30
        });
```

I cannot create a jsfiddle to demonstrate, since you cannot make a page refresh on jsfiddle.. :-)

Any Ideas?

Regards, Jan

**Comment by imakewebthings** [comment]
@janwidmer The sticky shortcut that you are trying to recreate uses a wrapper around the sticky element as the actual waypoint because of what you're seeing here. Making the waypoint itself "stuck" which I presume means `position:fixed` in your CSS, leads to problems in calculating its trigger point in the future. See http://imakewebthings.com/waypoints/guides/debugging/#fixed-position.

**Comment by janwidmer** [comment]
Hi Caleb, Thanks for your explanation.
