### ISSUE TITLE
this.group.first does not appear to be working in the UP direction

### ISSUE THREAD

**Issue by colincalnan** [imakewebthings/waypoints#472]
I can't get ```this.group.first()``` to trigger on up direction. It works in the down direction, but not in the up. 

Here's how I'm testing it

```javascript
$('.container').each(function() {
  new Waypoint({
    element: this,
    handler: function(direction) {
      if(this === this.group.first()) {
      console.dir('First in Group');
    },
    group: 'container'
  });
});
```

I'm also using the noframework js file.

**Comment by imakewebthings** [comment]
@colincalnan Seems to work for me: https://jsfiddle.net/imakewebthings/5zst8xj0/ Can you show me an example of your code not working?

**Comment by imakewebthings** [comment]
@colincalnan Closing this as cannot-reproduce. If you can provide an example I'll gladly reopen.
