### ISSUE TITLE
Youtube player fullscreen messes with waypoints and sends scroll to the top

### ISSUE THREAD

**Issue by dsvictorh** [imakewebthings/waypoints#475]
I have been working on a kind of peculiar site in which I found that every time I went fullscreen mode on the youtube embedded player the screen would flicker, freeze and then the site would immediately scroll at the top of the page. This stopped happening as soon as I removed the waypoints script.

After some research on my own implementation of the library and the library itself I found that all browsers but FF trigger the scroll and resize events when going fullscreen and that also triggered the scroll.waypoints and resize.waypoints events. It seems that on refreshing the waypoints it has the same functionality that when the page loads, meaning it tries to trigger waypoints that have already been passed by.

By restricting these events when we have fullscreen from an element in the document I managed to fix my own particular scenario:

* The content has to fade in and out when it enters/leaves the screen accordingly. 
* Some of these contents have a youtube player that needs to interrupt itself if the content fades out of the screen. We do this by removing the value of the 'src' attribute and putting it back. 
* When we trigger the fullscreen the waypoints refresh and identify themselves as being hit in the upwards direction.
* The action that has to remove the URL from 'src' happens while in fullscreen causing the page to lose the youtube video, thinking that it was at the top of the page and shows the page back at the top and in fullscreen mode.

I can't share the page because it is a work on progress and I'm under an NDA and I can't be sure if this won't happen unless you design a page with the same nature as this one but I can paste the modification I did to the script in order to fix this issue:

#### Original

```javascript
this.adapter.on('resize.waypoints', function() {
      if (!self.didResize) {
          self.didResize = true
          Waypoint.requestAnimationFrame(resizeHandler)
      }
})
```

#### Modified

```javascript
this.adapter.on('resize.waypoints', function() {
     if (!self.didResize) {
           if(!document.fullscreenElement &&
              !document.webkitFullscreenElement &&
              !document.mozFullScreenElement &&
              !document.msFullscreenElement){
                    self.didResize = true
                    Waypoint.requestAnimationFrame(resizeHandler)
              }
     }
})
```

#### Original

```javascript
this.adapter.on('scroll.waypoints', function() {
     if (!self.didScroll || Waypoint.isTouch) {
           self.didScroll = true
          Waypoint.requestAnimationFrame(scrollHandler)
      }
})
```

#### Modified: 

```javascript
this.adapter.on('scroll.waypoints', function() {
     if (!self.didScroll || Waypoint.isTouch) {
             if(!document.fullscreenElement &&
                !document.webkitFullscreenElement &&
                !document.mozFullScreenElement &&
                !document.msFullscreenElement){
                      self.didScroll = true
                      Waypoint.requestAnimationFrame(scrollHandler)
                }
   }
})
```

I understand this might be a solution that's too specific for the library but I wanted to share this in case someone finds a similar situation. We could technically just have a property to set the fullscreen behavior prevention IMO.

**Comment by imakewebthings** [comment]
@dsvictorh Perhaps you can listen for the `fullscreenchange` event and disable/enable waypoints.

```js
$(document).on('fullscreenchange webkitfullscreenchange mozfullscreenchange MSFullScreenChange', function () {
  if (document.fullscreenElement /* || all the other prefixes) {
    Waypoint.disableAll()
  }
  else {
    Waypoint.enableAll()
  }
})
```

**Comment by dsvictorh** [comment]
I think I tried something like that on a certain point and didn't quite help. I can't be 100% sure as I no longer have access to that project. If I can remember correctly it fixed the first jump but it would go crazy when the screen closed and opened repeatedly (e.g.: fullscreen, fullscreen out and then fullscreen again). 

Also for some reason this would also trigger the scroll events on browsers that were not FF, so even though your solution might work just fine we might need to include the scroll event as well

**Comment by imakewebthings** [comment]
@dsvictorh I imagine you also tried putting the fullscreen check into the waypoint handlers and exiting early if in fullscreen?

I hope you understand why I'm unlikely to put this into the main library and keep pitching other workaround suggestions. I certainly can't block off the use of Waypoints in fullscreen entirely, and I can't imagine adding a `noFullScreen` option with vague directions on why and when to use it. So I'm going to close this but feel free to keep discussing here if we can shake out some underlying problem.

**Comment by dsvictorh** [comment]
Yeah that's absolutely fine. Like I said in the case of anyone finding this particular issue (Which in my opinion was a terrible design but hey...Client is always right right?) they know how to deal with it. I agree it shouldn't be part of the library.  Also I tried thousands of things even delaying the re-enabling of the waypoints in a timeout to see if it was just a race condition going on....nothing. From my perspective I couldn't blame either of the libraries more than I could a weird design.
