### ISSUE TITLE
How to continuously trigger waypoints?

### ISSUE THREAD

**Issue by danyj** [imakewebthings/waypoints#476]
I am trying to use waypoints as infinite scroll to load additional items via ajax

	 $(holder).waypoint(function(direction) {
		
	   if (direction === 'down'){
			RunMasonryAjax();
	   }
	  
	}, {
		offset: 'bottom-in-view',
		continuous: true
	});  

the snipp above works only when I pass the bottom of the holder and than I have to scroll up/down for ajax function to fire again.

I know that waypoint also has own infinite scroll but it does not work for me since I am using different approach to load items.

It would be great if somehow I can refresh/destroy the waypoint once the items are loaded. 
Any help is appreciated.

**Comment by imakewebthings** [comment]
@danyj I suggest doing what the Infinite shortcut does: Destroy and recreate the waypoint each time.

```js
function createWaypoint () {
  $(holder).waypoint(function () {
    RunMasonryAjax(function () {
      createWaypoint()
    })
    this.destroy()
  }, {
    offset: 'bottom-in-view'
  })
}

createWaypoint()
```

Without knowing how your `RunMasonryAjax` function works, I wrote the above assuming that the callback passed to it runs when that ajax is finished loading. Adjust as needed.
