### ISSUE TITLE
waypoint infinite scroll only add second page

### ISSUE THREAD

**Issue by mototony** [imakewebthings/waypoints#477]
I'm using 4.0 waypoint and infinite,on my infinite page it;s only load second page and no more,
it's my code
```
var $footer = jQuery('.pagination'),
opts = {
	offset: '100%'
};
$footer.waypoint(function(event, direction) {
	
	$footer.waypoint('remove');
}, opts);

var infinite = new Waypoint.Infinite({
	element: document.getElementById('sy_container'),
	items: '.grid',
	loadingClass: 'infinite-loading',
       // it's using jquery first() because there have pagination and first active page using <span>
	more: jQuery('#more a').first(),
	offset: 'bottom-in-view',
	oonBeforePageLoad: function() { 
	
	},
	onAfterPageLoad:  function() {
			
			}
	})

```

Any help is greatly appreciated

**Comment by mototony** [comment]
Here is error message:
Error: No handler option passed to Waypoint constructor
throw new Error('No handler option passed to Waypoint constructor')

**Comment by imakewebthings** [comment]
I suspect the problem is your `more` option. From the docs:

> **more** *default: '.infinite-more-link'* This string selector should match the "Next Page" element on every page. Infinite will know to stop loading more pages when an AJAX request no longer includes this "More" link (indicating you're on the final page.)

You've passed it a jQuery object. It needs a string selector that will be used by `$()` to get the next more link.

**Comment by imakewebthings** [comment]
@mototony Oh, and the error you're seeing is because of this:

```js
$footer.waypoint(function(event, direction) {
    $footer.waypoint('remove');
}, opts);
```

All of that is using the old Waypoints 2.x jQuery plugin syntax. Specifically the problem is `$footer.waypoint('remove');`. You can't pass functions as string parameters to the jQ function anymore. You should replace that line with `this.remove();`
