### ISSUE TITLE
jQuery [data] attribute selector and waypoints

### ISSUE THREAD

**Issue by Smashr** [imakewebthings/waypoints#479]
Why would this work :

```
var elements = jQuery(".content_box");
elements.waypoint({
  handler: function(direction) {
    console.log('We have arrived');
  }
});
```

and this not:

```
var elements = jQuery("[data-reveal]");
elements.waypoint({
  handler: function(direction) {
    console.log('We have arrived');
  }
});
```

hopelessly baffled. Any help appreciated.

**Comment by imakewebthings** [comment]
@Smashr I don't know. Can I see the page? What do you get when you put a `console.log(elements.get())` between the query and the waypoint call in each case?

**Comment by imakewebthings** [comment]
@Smashr Closing. Can reopen with more information.
