### ISSUE TITLE
Issues with High Resolution displays?

### ISSUE THREAD

**Issue by roberts-interactive** [imakewebthings/waypoints#480]
I've been using Waypoints on a project for a while and recently switched from a Mac Pro with a 1920x1200 display to a Retina MacBook Pro. When the browser is on the internal retina display, Waypoints doesn't trigger a test console.log() output, but when on the lower res monitor, it works fine. If I have the browser on the internal display, I can go past the trigger point, then adjust the width and it will get triggered. This is driving me crazy. 

```
		var waypoint = new Waypoint({
		  element: document.getElementById('menu-button'),
		  handler: function() {
			  if($(".nav-menu").is(":visible"))
			  {
                                  console.log('working');
				  $(".top-bar-close").fadeToggle("slow").toggleClass("hide");
			  }
		  }
		});
```

**Comment by imakewebthings** [comment]
@roberts-interactive I'd need to see the page to diagnose this.

**Comment by imakewebthings** [comment]
@roberts-interactive Can reopen with more information.
