### ISSUE TITLE
How to delay waypoints for each grid item in order to create staggering effect?

### ISSUE THREAD

**Issue by danyj** [imakewebthings/waypoints#483]
@imakewebthings  Hi there , do you mind helping out here   http://stackoverflow.com/questions/35773296/how-to-delay-jquery-waypoint-for-each-item-in-order-to-create-staggering-effect  so that we can get the staggering effect to work properly. 

Any help is appreciated!

**Comment by imakewebthings** [comment]
http://stackoverflow.com/a/35789489/669712

**Comment by danyj** [comment]
:100:  thank you!
