### ISSUE TITLE
Broken license URL in distributed JS files

### ISSUE THREAD

**Issue by jdomingu** [imakewebthings/waypoints#484]
If you download the library from http://imakewebthings.com/waypoints/, the lib/*.js files includes a URL in the top comment like so:

https://github.com/imakewebthings/waypoints/blog/master/licenses.txt

The URL should say blob/ instead of blog/. This seems to be fine in the repo source--just not in the download.

**Comment by imakewebthings** [comment]
Fixed in the 4.0.1 release.
