### ISSUE TITLE
waypoints and scrollbar replacements

### ISSUE THREAD

**Issue by afrozl** [imakewebthings/waypoints#485]
I'm using simplebar (https://github.com/Grsmto/simplebar) for custom scrolbars, but unfortunately, when I apply it to an element that contains waypoints, they stop firing. Any suggestions on what could  be causing this? It appears to be related to scrollTop no longer returning teh correct values (always 0). I can get around that by hard coding the scrollTop method in the jquery adapter to use the simplebar equivalent - $(element).simplebar('getScrollElement').scrollTop() - but that doesn't seem optimal as it does not pick up the correct element and requires it to be passed in as an argument.

**Comment by imakewebthings** [comment]
@afrozl Custom scrollbar replacements generally work by making the container `overflow:hidden`, listening to wheel, key, and mouse events, and moving a content element inside the container using `marginTop` or `transform`. No scroll events are triggered, scroll top isn't changed, hence the custom implementation of `scrollTop`.

Here's where the adapter layer of waypoints does come in handy. If you can make an adapter that implements all the necessary methods and returns the right things using the simplebar methods, you can compile that with the core classes and get a `simplebar.waypoints.js`. That would be up to you, and I would include it in this repo or support it, but I would be happy to try to help you in compiling that file if you're actually interested in going down this path.

Besides that, your options are null. Use the custom scrolling or Waypoints but not both.
