### ISSUE TITLE
Events on waypoints hit?

### ISSUE THREAD

**Issue by ethanclevenger91** [imakewebthings/waypoints#487]
With generic waypoints, this is something I could do myself in the handler, but with shortcuts like Sticky Elements, I don't get a chance to do anything extra. 

Use case: I've got a secondary menu sliding out from offscreen when a button in the header is clicked. When the header gets stuck (on scroll), I'm removing some elements from it, including the button that triggers the menu, so I'd like to automatically close the menu if the header gets stuck. This would be easier with an event I could listen for.

Thoughts?

**Comment by imakewebthings** [comment]
An undocumented thing: Passing a `handler` option to the Sticky shortcut still calls that handler in addition to doing all the shortcut stuff: https://github.com/imakewebthings/waypoints/blob/720217ffe27642f78ef26b94929b151dc6694168/src/shortcuts/sticky.js#L29-L31

**Comment by ethanclevenger91** [comment]
Perfect, works as advertised. Thanks!
