### ISSUE TITLE
Semi colon key broken?

### ISSUE THREAD

**Issue by AlexNodex** [imakewebthings/waypoints#490]
Great library, however it's missing a lot of semi colons, while this might be fine for most minifiers/compilers, there are some that choke on it as they remove the whitespace between declarations and functions which wraps the next decalration to the preceeding thus breaking your code.

Might be an idea to add the semi colons after all var foo=function(){};... and all method calls :)

**Comment by imakewebthings** [comment]
There is a semicolon [at the end of every /lib file](https://github.com/imakewebthings/waypoints/blob/9bdcb2c982102eec2508f3c4964395171f325515/lib/jquery.waypoints.js#L649) to account for broken concatenaters. Concerning the other semicolons you're suggesting: They already exist, I've simply not typed them.

**Comment by AlexNodex** [comment]
Hi.

The semi colons at the end of the lib files don’t actually help the situation.

Things like 

Group.findOrCreate = function(options) {
return groups[options.axis][options.name] || new Group(options)
}

Need to be

Group.findOrCreate = function(options) {
return groups[options.axis][options.name] || new Group(options);
};

Else the minifiers break.

Regards

Alex

**Comment by imakewebthings** [comment]
@AlexNodex What minifier is this?

**Comment by AlexNodex** [comment]
http://joliclic.free.fr/php/javascript-packer/en/ for one, there are others though.

**Comment by imakewebthings** [comment]
@AlexNodex You need to file a bug report with that library. It is failing on 100% valid JavaScript.

**Comment by AlexNodex** [comment]
Hi.

I’ve been using it for years and it’s minifying fine.

Valid javascript might be OK to leave out semi colons but the whitespace it removes adds two lines together.

Almost every other (javascript) library I’ve ever used knows of quirks like this and adds semi colons to combat it.

At the end of the day it’s your code so do with it what you will but my advice is to add the semi colons, it also makes it more readable!

Regards

Alex
