### ISSUE TITLE
Project maintenance and development

### ISSUE THREAD

**Issue by Aweary** [imakewebthings/waypoints#491]
@imakewebthings looks like this project has been ignored for quite a while, do you plan on ever maintaining it? Just want to know if I should start my own fork or if you'd be open to adding contributors so someone else can maintain it.

**Comment by imakewebthings** [comment]
@Aweary Is there a specific bug that prompted this issue? The library is generally stable and a plan for 5.0 and 4.x loosely described [here](https://github.com/imakewebthings/waypoints/pull/481#issuecomment-193627205).

To answer your question: I plan on resuming active maintainance of it once the combination of work + newborn affords me more than 10 minutes of extracurricular time each day (which I'm using to write this!) That **will** happen, but it is likely measured in months. If you cannot wait that long, please do what you need in a fork.

Keeping this open in case anyone else was wondering.

**Comment by Aweary** [comment]
@imakewebthings nothing in particular, I was just reviewing some options for an upcoming feature implementation and I usually prefer to use repos that I feel will respond to issues that we may have. I saw there were 18 open issues with little activity so I wanted to see the status.

I can definitely understand not having enough free time 😄  Are you the only maintainer?

**Comment by imakewebthings** [comment]
@Aweary Yes.
