### ISSUE TITLE
Sticky element on scrolling problem ( touch devices )

### ISSUE THREAD

**Issue by SempaChoo** [imakewebthings/waypoints#492]
I am having a problem with my sticky header on iPad and couple of other touch devices.. I am using your plugin to detect when my element is in view and i stick it at the top and it works fine on desktops and laptops but not on ipads and mobiles. Problem is that every time i scroll window I have to wait until scrolling is finished and my sticky element is updated.. Please provide me with some tips or workaround, thx.

**Comment by justinmetros** [comment]
Most mobile and touch devices don't fire scroll events like desktops. On a desktop, using a mouse or touchpad, scroll events fire constantly. In many situations they fire so fast we actually need to throttle or debounce them. Waypoints is well suited for this situation.

On some ( if not most ) mobile devices, this is not the case. The scroll events fire only at the start and end of the scroll. This is why you see the waypoint pop into action only after it has stopped.

Demo of this in action:
http://andyshora.com/mobile-scroll-event-problems.html

Here is another example / demo with some less than ideal workarounds. 
https://www.tjvantoll.com/2012/08/19/onscroll-event-issues-on-mobile-browsers/

Both those links are a few years old but the problem has been around for a while so completely relevant.

Spoiler alert - unless you're building a native mobile application ( where waypoints probably isnt as relevant ), you may want to go ahead and just disable that sticky header on touch devices using something like [Modernizr] (https://modernizr.com/) or [Feature.js] ( http://featurejs.com/ )

You could also try something like [headroom.js] (http://wicky.nillia.ms/headroom.js/)

**Comment by SempaChoo** [comment]
@justinmetros thank you very much on a such a great explanation! Cheers.
