### ISSUE TITLE
Option for disabling resize event

### ISSUE THREAD

**Issue by sjelfull** [imakewebthings/waypoints#494]
Hey, in my apps, I usually have 1 event handler for browser resizing, and brodcasts that to any part that needs to know.

In Waypoints case, I would have a handler for refreshing all waypoints when needed:

```javascript
onResize: function() {
    this.waypoints.refreshAll();
}
```

Could you add a option to disable the resize handling built-in to Waypoints?

**Comment by imakewebthings** [comment]
Interesting. Would you be willing to share what bugs come up in your use case from having the two separate handlers?

If you want to kill all the resizes today:

```js
Context.prototype.createThrottledResizeHandler = function() {}
```

Or if you want to kill it on only one context, the `Adapter` interface includes a jQuery style `off` method:

```js
someWaypoint.context.adapter.off('resize')
```

**Comment by sjelfull** [comment]
Ah, I didn't actually experience any bugs. 

I just like to know that I only have one handler for each type of events that might cause performance problems, like scroll and resize.

I noticed that you use requestAnimationFrame, so your probably doing it in a smart way. Most libraries are not that careful, though. That's why I prefer to handle that myself normally, if the library in question offers a way to do a manual refresh.

Does it make sense to you? I guess another case might be where you want to temporarily disable the resize refresh for some reason. 

Is it possible to add a `on/off` global method?

**Comment by imakewebthings** [comment]
@sjelfull Each `Context` has a resize handler. If you are like 95% of folks, `window` is your only Context. There is only one resize handler. And like you saw, it is throttled against `requestAnimationFrame`.

I'm going to pass on adding the option, though you're of course free to use the methods I showed above to do it yourself. I think it adds to the API surface without providing value for the vast vast vast majority of users.

**Comment by sjelfull** [comment]
Thanks for considering. The methods above should be sufficient, if I ever have the need.
