### ISSUE TITLE
No main in package.json

### ISSUE THREAD

**Issue by bl4ckdu5t** [imakewebthings/waypoints#495]
Without the main entry in the package.json, the package can't be successfully used through browserify/webpack require. I'd simply just add a main. I considered it may have been skipped because there are different possible main i.e the noframework, zepto, or jQuery builds but when I try to relatively require those. There's no part of the code that exports the module.

**Comment by imakewebthings** [comment]
Duplicate of #458. Aware of the problem w/ a roadmap to fix it.

**Comment by derwaldgeist** [comment]
> w/ a roadmap to fix it

When exactly? ;-)
