### ISSUE TITLE
Active states for menu items

### ISSUE THREAD

**Issue by aaronstezycki** [imakewebthings/waypoints#498]
Hi guys, not sure if I'm doing this correctly 100% but I've given it a go several times just to fail at the last hurdle. 

Ive got pen here https://codepen.io/aaron-stez/pen/beeyVa, which I'm trying to achieve the same effect used in this pen https://codepen.io/jakob-e/pen/mhCyx. Simply put I want active states on my `.jump-list li a` when I enter the sections that correspond to menu item I've clicked on or scrolled into. 

I've tried using the Inview shortcut but can't seem to get that working either.

I'm not much of a javascript dev, so forgive me if I'm tripping over something silly. 

Any help is appreciated. Thanks in advance.

**Comment by imakewebthings** [comment]
I do something like this https://codepen.io/imakewebthings/pen/WxGaOz.
