### ISSUE TITLE
Is it possible to set offset to something like "bottom-in-view" + 100

### ISSUE THREAD

**Issue by simbunch** [imakewebthings/waypoints#500]
What I'm trying to achieve is for the "next" call for Infinite to be triggered when the bottom of the element is still about 100px below the viewport, so users need not wait till they have scrolled all way way to the bottom before it's triggered.

**Comment by imakewebthings** [comment]
@simbunch You can use a [function offset](http://imakewebthings.com/waypoints/api/offset-option/#function) to do this and any other fancy dynamic calculations you would like to. The "bottom-in-view" offset is itself nothing more than an alias for a [predefined function offset](https://github.com/imakewebthings/waypoints/blob/1d90d5bdeeee614161b94ab9f54880f027d52b73/src/waypoint.js#L155-L157)

**Comment by LorenBaxter** [comment]
>   offset: function () {
    return this.context.innerHeight() - this.adapter.outerHeight() - 100
  }

FYI, when implementing this on my own, I had to use + 100 rather than - 100 for the offset to work. Took a minute to figure out so thought I'd note it here.

**Comment by jsit** [comment]
I have an element that *begins* fixed to the bottom of the window, and that I want to *unstick* when it passes its "natural"/unfixed position near the bottom of the entire page (but not at the very bottom). For this I had to do:

```javascript
offset: function () {
  return this.context.innerHeight() - this.element.firstChild.offsetHeight;
}
```

Is there an easier way to accomplish this?

**Comment by abirsikder** [comment]
@imakewebthings  hello 

how can i add dual offset in percentage like 50% -50% in jquery ?????

**Comment by fallenturtle** [comment]
> ```js
> offset: function () {
>   return this.context.innerHeight() - this.element.firstChild.offsetHeight;
> }
> ```

I'm trying to do this to. This code looks like it should work, but for some reason it leads to a constant activating/deactivating of the element's fixed property.
