### ISSUE TITLE
Shortcuts as part of $.fn.waypoint

### ISSUE THREAD

**Issue by fvpDev** [imakewebthings/waypoints#502]
Hi Caleb! I'm not sure of the logic behind this at all but I was wondering if there is any way to declare a new sticky like `$(selector).waypoint.sticky()` instead of having to do `new Waypoint.Sticky()`?

Loving this btw. I packaged v4.0.0 for use with meteor.js `meteor add fvpdev:jquery-waypoints`

**Comment by imakewebthings** [comment]
@fvpDev There isn't. There used to be. I'm more likely to keep moving in that direction, away from jQuery, in the future.
