### ISSUE TITLE
Make it compatible with browserify/require js

### ISSUE THREAD

**Issue by cjroebuck** [imakewebthings/waypoints#52]
I had to hack waypoints to make it work with browserify, as `this` is incorrectly set when requiring it in.

The change I made was to the arguments being passed in to the self executing function, on the last line of waypoints:

`})(jQuery, 'waypoint', 'waypoints', window);`

**Comment by crispouille** [comment]
Looking for an up, i'm on it actually with browserify + vueify (vueJS) :( @cappslock  @cjroebuck  @imakewebthings
