### ISSUE TITLE
How to add multiple items for Waypoints Inview

### ISSUE THREAD

**Issue by pashkes** [imakewebthings/waypoints#560]
No duplication of code

**Comment by Hujjat** [comment]
Explain more, what you really want and what you have done so far. ?

**Comment by jitendersandhu** [comment]
I also have the similar use case.

*Use Case:*

Play/Pause `HTML5 video` when user scrolls and the video enters/leaves the viewport.

In my use case, there can be multiple videos on the page. Hence, if there is an option to provide an array of elements to `Waypoint Inview` method, that would be great as i can avoid the `each` loop to do the same.

Here is what i am currently doing:

```javascript
$('video[data-waypoint-in-view="enabled"]').each(function(index, vid) {
    var inview = new Waypoint.Inview({
        element: $(this),
        enter: function(direction) {
            vid.play();
        },
        exited: function(direction) {
            vid.pause();
        }
    });
});
```

With `Waypoint inView` accepting array of elements, i can simply do following:

```javascript
var inview = new Waypoint.Inview({
        elements: $('video[data-waypoint-in-view="enabled"]'),
        enter: function(direction) {
            vid.play();
        },
        exited: function(direction) {
            vid.pause();
        }
});
```

Thanks in advance!

@Hujjat @imakewebthings

**Comment by jakub-gawryl** [comment]
I agree but with one little modification: each method (enter, entered, exit exited) should return element on which this method was called.
