### ISSUE TITLE
offsets for different scroll directions?

### ISSUE THREAD

**Issue by jedierikb** [imakewebthings/waypoints#81]
It is easy to determine if I am scrolling up or down.

However, I would like to trigger events when an element first comes into view from the top or the bottom.

Since I can only set one offset, how do I do this?

Adding an additional element.waypoint( ... ) seems to override the behavior of the first one. :-/

**Comment by stratboy** [comment]
You can find the solution here:

https://github.com/imakewebthings/waypoints/issues/12

and the original answer:

https://stackoverflow.com/questions/19181435/different-offset-for-jquery-waypoint-up-event
